/** QL_TC_2026 — Apps Script API cho toàn bộ 17 phân hệ. */
const APP_CONFIG=Object.freeze({spreadsheetId:'1fA0W5tx3WzEzlHEKca2ysodHUKFM3_OgyOB3a7PlpCc',title:'QL_TC_2026',timeZone:'Asia/Ho_Chi_Minh',maxRowsPerModule:5000,maxLogRows:2000});
const ST=['NHAP','CHO_DUYET','DA_DUYET','DA_THUC_HIEN','HOAN_THANH','HUY'];
const APP_MODULES=Object.freeze({
 THU_CHI:{title:'Thu chi (dữ liệu cũ)',group:'Dòng tiền',idField:'MA_GIAO_DICH',required:['LOAI_GIAO_DICH','LOAI_BAN_GHI','NGAY_DU_KIEN','NOI_DUNG','SO_TIEN'],enums:{LOAI_GIAO_DICH:['THU','CHI'],LOAI_BAN_GHI:['KE_HOACH','THUC_TE'],TRANG_THAI:ST},dates:['NGAY_DU_KIEN','NGAY_THUC_TE'],amounts:['SO_TIEN','TY_GIA_QUY_DOI'],columns:['NGAY_DU_KIEN','LOAI_GIAO_DICH','LOAI_BAN_GHI','NOI_DUNG','MA_TAI_KHOAN','SO_TIEN','TRANG_THAI']},
 TAI_KHOAN:{title:'Tài khoản',group:'Dòng tiền',idField:'MA_TAI_KHOAN',required:['TEN_TAI_KHOAN','LOAI_TAI_KHOAN','MA_TIEN_TE'],enums:{LOAI_TAI_KHOAN:['TIEN_MAT','NGAN_HANG','VI_DIEN_TU','KHAC'],TRANG_THAI:['HOAT_DONG','NGUNG_HOAT_DONG']},columns:['TEN_TAI_KHOAN','MA_CONG_TY','LOAI_TAI_KHOAN','MA_NGAN_HANG','SO_TAI_KHOAN','MA_TIEN_TE','TRANG_THAI']},
 SO_DU_DAU_KY:{title:'Số dư đầu kỳ',group:'Dòng tiền',idField:'MA_SO_DU',required:['MA_TAI_KHOAN','NGAY_CHOT','SO_DU'],dates:['NGAY_CHOT'],amounts:['SO_DU'],columns:['NGAY_CHOT','MA_TAI_KHOAN','MA_TIEN_TE','SO_DU','GHI_CHU']},
 KE_HOACH_THU_CHI:{title:'Kế hoạch thu chi',group:'Dòng tiền',idField:'MA_KE_HOACH',required:['KY_BAO_CAO','LOAI_THU_CHI','NOI_DUNG','NGAY_DU_KIEN','SO_TIEN_DU_KIEN'],enums:{LOAI_THU_CHI:['THU','CHI'],TRANG_THAI:ST},dates:['NGAY_DU_KIEN'],amounts:['SO_TIEN_DU_KIEN'],columns:['KY_BAO_CAO','LOAI_THU_CHI','NGAY_DU_KIEN','NOI_DUNG','MA_CONG_TY','MA_DU_AN','SO_TIEN_DU_KIEN','TRANG_THAI']},
 GIAO_DICH_TIEN:{title:'Giao dịch tiền',group:'Dòng tiền',idField:'MA_GIAO_DICH',required:['NGAY_THUC_TE','LOAI_GIAO_DICH','SO_TIEN','NOI_DUNG'],enums:{LOAI_GIAO_DICH:['THU','CHI','CHUYEN_NOI_BO'],LOAI_DONG_TIEN:['VAN_HANH','DAU_TU','TAI_CHINH','NOI_BO'],TRANG_THAI:ST},dates:['NGAY_THUC_TE','NGAY_THUC_HIEN','NGAY_DOI_SOAT'],amounts:['SO_TIEN','TY_GIA_QUY_DOI'],columns:['NGAY_THUC_TE','LOAI_GIAO_DICH','LOAI_DONG_TIEN','NOI_DUNG','MA_TAI_KHOAN_NGUON','MA_TAI_KHOAN_DICH','SO_TIEN','TRANG_THAI']},
 NGUON_VON:{title:'Nguồn vốn',group:'Nguồn vốn & vay',idField:'MA_NGUON_VON',required:['LOAI_NGUON','KY_DU_KIEN'],enums:{LOAI_NGUON:['VAY','THU_BAN_HANG','TIEN_QUAY_VE','VON_NOI_BO','KHAC'],TRANG_THAI:['DU_KIEN','CHO_DUYET','DA_DUYET','GIAI_NGAN_MOT_PHAN','DA_GIAI_NGAN','KHONG_THUC_HIEN']},dates:['NGAY_DU_KIEN','NGAY_THUC_NHAN'],amounts:['SO_TIEN_DAT_DU_KIEN','SO_TIEN_XD_DU_KIEN','SO_TIEN_KHAC_DU_KIEN','TONG_DU_KIEN','SO_TIEN_DA_DUYET','SO_TIEN_DA_GIAI_NGAN','CO_THE_GIAI_NGAN','KHONG_THE_GIAI_NGAN','DU_NO_PHAI_TRA'],calculated:['TONG_DU_KIEN'],autoColumns:['CO_THE_GIAI_NGAN','KHONG_THE_GIAI_NGAN','DU_NO_PHAI_TRA','GHI_CHU'],columns:['KY_DU_KIEN','LOAI_NGUON','NOI_DUNG_PHUONG_AN','TONG_DU_KIEN','SO_TIEN_DA_DUYET','SO_TIEN_DA_GIAI_NGAN','CO_THE_GIAI_NGAN','KHONG_THE_GIAI_NGAN','DU_NO_PHAI_TRA','NGAY_DU_KIEN','TRANG_THAI','GHI_CHU']},
 KHOAN_VAY:{title:'Khoản vay',group:'Nguồn vốn & vay',idField:'MA_KHOAN_VAY',required:['TEN_KHOAN_VAY','HAN_MUC_VAY'],enums:{LOAI_LAI_SUAT:['CO_DINH','THA_NOI','KHAC'],TRANG_THAI:['DU_KIEN','DANG_VAY','DA_TAT_TOAN','TAM_DUNG']},dates:['NGAY_KY','NGAY_GIAI_NGAN_DAU','NGAY_DAO_HAN','NGAY_CHOT_DU_NO_DAU_KY','NGAY_GOC_BAN_DAU'],amounts:['HAN_MUC_VAY','TONG_GOC_GIAI_NGAN','DU_NO_GOC_BAN_DAU','DU_NO_GOC_DAU_KY'],percents:['LAI_SUAT_NAM'],autoColumns:['DU_NO_GOC_DAU_KY','NGAY_CHOT_DU_NO_DAU_KY','DU_NO_GOC_BAN_DAU','NGAY_GOC_BAN_DAU'],columns:['TEN_KHOAN_VAY','MA_NGAN_HANG','SO_HOP_DONG','HAN_MUC_VAY','TONG_GOC_GIAI_NGAN','DU_NO_GOC_BAN_DAU','DU_NO_GOC_DAU_KY','NGAY_CHOT_DU_NO_DAU_KY','LAI_SUAT_NAM','NGAY_DAO_HAN','TRANG_THAI']},
 LICH_SU_LAI_SUAT:{title:'Lịch sử lãi suất',group:'Nguồn vốn & vay',idField:'MA_LICH_SU',required:['MA_KHOAN_VAY','NGAY_AP_DUNG','LAI_SUAT_NAM'],dates:['NGAY_AP_DUNG'],percents:['LAI_SUAT_NAM','CO_SO_LAI_SUAT','BIEN_DO'],columns:['MA_KHOAN_VAY','NGAY_AP_DUNG','LAI_SUAT_NAM','CO_SO_LAI_SUAT','BIEN_DO','GHI_CHU']},
 LICH_TRA_NO:{title:'Lịch trả nợ',group:'Nguồn vốn & vay',idField:'MA_LICH_TRA',required:['MA_KHOAN_VAY','KY_TRA_NO','NGAY_DEN_HAN'],enums:{TRANG_THAI:['DU_KIEN','DEN_HAN','DA_TRA_MOT_PHAN','DA_THANH_TOAN','QUA_HAN','HUY']},dates:['NGAY_DEN_HAN'],amounts:['TONG_DU_NO','GOC_PHAI_TRA','DU_NO_SAU_KHI_TRA','LAI_PHAI_TRA','PHI_PHAI_TRA','DIEU_CHINH_TANG_GIAM','TONG_DA_THANH_TOAN'],calculated:['TONG_DU_NO','DU_NO_SAU_KHI_TRA','TONG_DA_THANH_TOAN'],virtual:['TONG_DU_NO','DU_NO_SAU_KHI_TRA','TONG_DA_THANH_TOAN'],allowNegative:['DIEU_CHINH_TANG_GIAM'],columns:['MA_KHOAN_VAY','KY_TRA_NO','NGAY_DEN_HAN','TONG_DU_NO','GOC_PHAI_TRA','DU_NO_SAU_KHI_TRA','LAI_PHAI_TRA','PHI_PHAI_TRA','DIEU_CHINH_TANG_GIAM','TRANG_THAI']},
 PHAN_BO_TRA_NO:{title:'Phân bổ trả nợ',group:'Nguồn vốn & vay',idField:'MA_PHAN_BO',required:['MA_LICH_TRA','MA_GIAO_DICH','NGAY_THANH_TOAN'],dates:['NGAY_THANH_TOAN'],amounts:['GOC_DA_TRA','LAI_DA_TRA','PHI_DA_TRA'],columns:['MA_LICH_TRA','MA_GIAO_DICH','NGAY_THANH_TOAN','GOC_DA_TRA','LAI_DA_TRA','PHI_DA_TRA','GHI_CHU']},
 CONG_NO:{title:'Công nợ',group:'Công nợ',idField:'MA_CONG_NO',required:['LOAI_CONG_NO','MA_DOI_TAC','NGAY_PHAT_SINH','SO_TIEN_GOC'],enums:{LOAI_CONG_NO:['PHAI_THU','PHAI_TRA'],TRANG_THAI:['MOI','DEN_HAN','THANH_TOAN_MOT_PHAN','DA_THANH_TOAN','QUA_HAN','HUY']},dates:['NGAY_PHAT_SINH','HAN_THANH_TOAN'],amounts:['SO_TIEN_GOC'],columns:['LOAI_CONG_NO','MA_DOI_TAC','SO_HOP_DONG','SO_HOA_DON','NGAY_PHAT_SINH','HAN_THANH_TOAN','SO_TIEN_GOC','TRANG_THAI']},
 PHAN_BO_CONG_NO:{title:'Phân bổ công nợ',group:'Công nợ',idField:'MA_PHAN_BO',required:['MA_CONG_NO','MA_GIAO_DICH','SO_TIEN_PHAN_BO','NGAY_PHAN_BO'],dates:['NGAY_PHAN_BO'],amounts:['SO_TIEN_PHAN_BO'],columns:['MA_CONG_NO','MA_GIAO_DICH','SO_TIEN_PHAN_BO','NGAY_PHAN_BO','GHI_CHU']},
 CHUNG_TU:{title:'Chứng từ',group:'Kiểm soát',idField:'MA_CHUNG_TU',required:['LOAI_BAN_GHI','MA_BAN_GHI','LOAI_CHUNG_TU'],dates:['NGAY_CHUNG_TU'],columns:['LOAI_BAN_GHI','MA_BAN_GHI','LOAI_CHUNG_TU','SO_CHUNG_TU','NGAY_CHUNG_TU','TEN_FILE','URL_FILE']},
 PHE_DUYET:{title:'Phê duyệt',group:'Kiểm soát',idField:'MA_PHE_DUYET',required:[],dates:['THOI_GIAN'],readOnly:true,columns:['THOI_GIAN','LOAI_BAN_GHI','MA_BAN_GHI','TRANG_THAI_TRUOC','TRANG_THAI_SAU','QUYET_DINH','EMAIL_NGUOI_DUYET']},
 DANH_MUC:{title:'Danh mục',group:'Hệ thống',idField:'MA',required:['LOAI_DANH_MUC','TEN'],enums:{TRANG_THAI:['HOAT_DONG','NGUNG_HOAT_DONG']},columns:['LOAI_DANH_MUC','MA','TEN','TRANG_THAI','GHI_CHU'],manualId:true},
 NGUOI_DUNG:{title:'Người dùng',group:'Hệ thống',idField:'EMAIL',required:['HO_TEN','VAI_TRO'],enums:{VAI_TRO:['ADMIN','TAI_CHINH','KE_TOAN','NHAP_LIEU','NGUOI_DUYET','QUAN_LY'],TRANG_THAI:['HOAT_DONG','NGUNG_HOAT_DONG']},columns:['EMAIL','HO_TEN','VAI_TRO','TRANG_THAI','GHI_CHU'],manualId:true,adminOnly:true},
 NHAT_KY:{title:'Nhật ký',group:'Hệ thống',idField:'MA_NHAT_KY',required:[],dates:['THOI_GIAN'],readOnly:true,adminOnly:true,columns:['THOI_GIAN','EMAIL_NGUOI_DUNG','CHUC_NANG','MA_BAN_GHI','HANH_DONG','NOI_DUNG_THAY_DOI']}
});
const ROLE_RULES=Object.freeze({ADMIN:{write:true,approve:true,remove:true},TAI_CHINH:{write:true,approve:false,remove:false},KE_TOAN:{write:true,approve:false,remove:false},NHAP_LIEU:{write:true,approve:false,remove:false},NGUOI_DUYET:{write:false,approve:true,remove:false},QUAN_LY:{write:false,approve:false,remove:false},VIEWER:{write:false,approve:false,remove:false}});

/** Cấu hình giao diện: trường thời gian, bộ lọc, tác vụ; V5.6 thêm card (thẻ mobile Design 1) và metrics (chỉ số tổng tính trên toàn bộ kết quả lọc). */
const UI_MODULES=Object.freeze({
 THU_CHI:{dateField:'NGAY_DU_KIEN',filters:['LOAI_GIAO_DICH','LOAI_BAN_GHI','MA_TAI_KHOAN','TRANG_THAI'],actions:['VIEW','EDIT','SUBMIT','CANCEL'],card:{lead:'type:LOAI_GIAO_DICH',title:'NOI_DUNG',sub:['LOAI_BAN_GHI','MA_TAI_KHOAN'],amount:'SO_TIEN',date:'NGAY_DU_KIEN'},metrics:[{l:'Tổng thu',sum:'SO_TIEN',where:{LOAI_GIAO_DICH:'THU'},not:{TRANG_THAI:['HUY']}},{l:'Tổng chi',sum:'SO_TIEN',where:{LOAI_GIAO_DICH:'CHI'},not:{TRANG_THAI:['HUY']}},{l:'Chênh lệch',diff:[0,1]}]},
 TAI_KHOAN:{filters:['MA_CONG_TY','LOAI_TAI_KHOAN','MA_NGAN_HANG','MA_TIEN_TE','TRANG_THAI'],actions:['VIEW','CREATE','EDIT','TOGGLE'],card:{lead:'bank:MA_NGAN_HANG',title:'TEN_TAI_KHOAN',sub:['SO_TAI_KHOAN','MA_CONG_TY'],date:'MA_TIEN_TE'},metrics:[{l:'Tổng tài khoản',count:1},{l:'Đang hoạt động',count:1,where:{TRANG_THAI:'HOAT_DONG'}},{l:'Ngừng hoạt động',count:1,where:{TRANG_THAI:'NGUNG_HOAT_DONG'}}]},
 SO_DU_DAU_KY:{dateField:'NGAY_CHOT',filters:['MA_TAI_KHOAN','MA_TIEN_TE'],actions:['VIEW','CREATE','EDIT','COPY_PERIOD'],card:{lead:'bank:MA_TAI_KHOAN',title:'MA_TAI_KHOAN',sub:['MA_TIEN_TE','GHI_CHU'],amount:'SO_DU',date:'NGAY_CHOT'},metrics:[{l:'Tổng số dư',sum:'SO_DU'},{l:'Số bản ghi',count:1}]},
 KE_HOACH_THU_CHI:{dateField:'NGAY_DU_KIEN',periodField:'KY_BAO_CAO',filters:['LOAI_THU_CHI','MA_CONG_TY','MA_DU_AN','MA_NHOM_THU_CHI','TRANG_THAI'],actions:['VIEW','CREATE','EDIT','DUPLICATE','SUBMIT','APPROVE','REJECT','CREATE_TRANSACTION','CANCEL'],card:{lead:'type:LOAI_THU_CHI',title:'NOI_DUNG',sub:['MA_DU_AN','KY_BAO_CAO'],amount:'SO_TIEN_DU_KIEN',date:'NGAY_DU_KIEN'},metrics:[{l:'Dự kiến thu',sum:'SO_TIEN_DU_KIEN',where:{LOAI_THU_CHI:'THU'},not:{TRANG_THAI:['HUY']}},{l:'Dự kiến chi',sum:'SO_TIEN_DU_KIEN',where:{LOAI_THU_CHI:'CHI'},not:{TRANG_THAI:['HUY']}},{l:'Chênh lệch',diff:[0,1]},{l:'Chờ duyệt',count:1,where:{TRANG_THAI:'CHO_DUYET'}}]},
 GIAO_DICH_TIEN:{dateField:'NGAY_THUC_TE',filters:['LOAI_GIAO_DICH','LOAI_DONG_TIEN','MA_TAI_KHOAN_NGUON','MA_TAI_KHOAN_DICH','TRANG_THAI'],actions:['VIEW','CREATE','EDIT','SUBMIT','APPROVE','COMPLETE','RECONCILE','DOCUMENT','CANCEL'],card:{lead:'type:LOAI_GIAO_DICH',title:'NOI_DUNG',sub:['MA_TAI_KHOAN_NGUON','MA_TAI_KHOAN_DICH'],amount:'SO_TIEN',date:'NGAY_THUC_TE'},metrics:[{l:'Đã thu',sum:'SO_TIEN',where:{LOAI_GIAO_DICH:'THU',TRANG_THAI:['DA_DUYET','DA_THUC_HIEN','HOAN_THANH']}},{l:'Đã chi',sum:'SO_TIEN',where:{LOAI_GIAO_DICH:'CHI',TRANG_THAI:['DA_DUYET','DA_THUC_HIEN','HOAN_THANH']}},{l:'Chuyển nội bộ',sum:'SO_TIEN',where:{LOAI_GIAO_DICH:'CHUYEN_NOI_BO',TRANG_THAI:['DA_DUYET','DA_THUC_HIEN','HOAN_THANH']}},{l:'Ròng',diff:[0,1]}]},
 NGUON_VON:{dateField:'NGAY_DU_KIEN',periodField:'KY_DU_KIEN',filters:['LOAI_NGUON','MA_CONG_TY','MA_DU_AN','MA_NGAN_HANG','TRANG_THAI'],actions:['VIEW','CREATE','EDIT','SUBMIT','APPROVE','DISBURSE','LINK','CANCEL'],card:{lead:'text:LOAI_NGUON',title:'NOI_DUNG_PHUONG_AN',sub:['CO_THE_GIAI_NGAN','KHONG_THE_GIAI_NGAN'],amount:'TONG_DU_KIEN',date:'NGAY_DU_KIEN'},metrics:[{l:'Tổng dự kiến',sum:'TONG_DU_KIEN',not:{TRANG_THAI:['KHONG_THUC_HIEN']}},{l:'Đã duyệt',sum:'SO_TIEN_DA_DUYET',not:{TRANG_THAI:['KHONG_THUC_HIEN']}},{l:'Đã giải ngân',sum:'SO_TIEN_DA_GIAI_NGAN',not:{TRANG_THAI:['KHONG_THUC_HIEN']}},{l:'Có thể giải ngân',sum:'CO_THE_GIAI_NGAN',not:{TRANG_THAI:['KHONG_THUC_HIEN']}},{l:'Không thể giải ngân',sum:'KHONG_THE_GIAI_NGAN',not:{TRANG_THAI:['KHONG_THUC_HIEN']}}]},
 KHOAN_VAY:{noPaging:true,dateField:'NGAY_DAO_HAN',fallbackDateField:'NGAY_CHOT_DU_NO_DAU_KY',filters:['MA_CONG_TY_VAY','MA_DU_AN','MA_NGAN_HANG','LOAI_LAI_SUAT','TRANG_THAI'],actions:['VIEW','CREATE','EDIT','ADD_RATE','CREATE_SCHEDULE','VIEW_SCHEDULE','PAUSE','SETTLE'],card:{lead:'bank:MA_NGAN_HANG',title:'TEN_KHOAN_VAY',sub:['SO_HOP_DONG','LAI_SUAT_NAM'],amount:'DU_NO_GOC_DAU_KY',date:'NGAY_DAO_HAN'},metrics:[{l:'Tổng hạn mức',sum:'HAN_MUC_VAY'},{l:'Đã giải ngân',sum:'TONG_GOC_GIAI_NGAN'},{l:'Dư nợ đầu kỳ',sum:'DU_NO_GOC_DAU_KY'},{l:'Đang vay',count:1,where:{TRANG_THAI:'DANG_VAY'}}]},
 LICH_SU_LAI_SUAT:{dateField:'NGAY_AP_DUNG',filters:['MA_KHOAN_VAY'],actions:['VIEW','CREATE','EDIT','OPEN_LOAN'],card:{lead:'bank:MA_KHOAN_VAY',title:'MA_KHOAN_VAY',sub:['CO_SO_LAI_SUAT','BIEN_DO'],amount:'LAI_SUAT_NAM',date:'NGAY_AP_DUNG'},metrics:[{l:'Số lần điều chỉnh',count:1}]},
 LICH_TRA_NO:{noPaging:true,monthNav:true,dateField:'NGAY_DEN_HAN',filters:['MA_KHOAN_VAY','TRANG_THAI'],actions:['COPY_MONTH','VIEW','CREATE','EDIT','PAY','ADJUST','ALLOCATE','OPEN_LOAN','CANCEL'],card:{lead:'bank:MA_KHOAN_VAY',title:'MA_LICH_TRA',sub:['MA_KHOAN_VAY','DU_NO_SAU_KHI_TRA'],amount:'TONG_THANH_TOAN',date:'NGAY_DEN_HAN'},metrics:[{l:'Tổng dư nợ đầu kỳ',firstBy:{group:'MA_KHOAN_VAY',order:'NGAY_DEN_HAN',field:'TONG_DU_NO'}},{l:'Tổng gốc phải trả',sum:'GOC_PHAI_TRA'},{l:'Tổng dư nợ sau khi trả',lastBy:{group:'MA_KHOAN_VAY',order:'NGAY_DEN_HAN',field:'DU_NO_SAU_KHI_TRA'}},{l:'Lãi phải trả',sum:'LAI_PHAI_TRA'},{l:'Tổng thanh toán',sum:['GOC_PHAI_TRA','LAI_PHAI_TRA','PHI_PHAI_TRA','DIEU_CHINH_TANG_GIAM']}]},
 PHAN_BO_TRA_NO:{dateField:'NGAY_THANH_TOAN',filters:['MA_LICH_TRA','MA_GIAO_DICH'],actions:['VIEW','CREATE','EDIT','CANCEL','OPEN_SCHEDULE','OPEN_TRANSACTION'],card:{lead:'text:MA_LICH_TRA',title:'MA_LICH_TRA',sub:['MA_GIAO_DICH','GHI_CHU'],amount:'GOC_DA_TRA',date:'NGAY_THANH_TOAN'},metrics:[{l:'Gốc đã trả',sum:'GOC_DA_TRA'},{l:'Lãi đã trả',sum:'LAI_DA_TRA'},{l:'Phí đã trả',sum:'PHI_DA_TRA'},{l:'Tổng đã trả',add:[0,1,2]}]},
 CONG_NO:{dateField:'HAN_THANH_TOAN',filters:['LOAI_CONG_NO','MA_DOI_TAC','TRANG_THAI'],actions:['VIEW','CREATE','EDIT','PAY','ALLOCATE','OVERDUE','CANCEL'],card:{lead:'type:LOAI_CONG_NO',title:'MA_DOI_TAC',sub:['SO_HOA_DON','SO_HOP_DONG'],amount:'SO_TIEN_GOC',date:'HAN_THANH_TOAN'},metrics:[{l:'Phải thu',sum:'SO_TIEN_GOC',where:{LOAI_CONG_NO:'PHAI_THU'},not:{TRANG_THAI:['HUY']}},{l:'Phải trả',sum:'SO_TIEN_GOC',where:{LOAI_CONG_NO:'PHAI_TRA'},not:{TRANG_THAI:['HUY']}},{l:'Quá hạn',count:1,where:{TRANG_THAI:'QUA_HAN'}}]},
 PHAN_BO_CONG_NO:{dateField:'NGAY_PHAN_BO',filters:['MA_CONG_NO','MA_GIAO_DICH'],actions:['VIEW','CREATE','EDIT','CANCEL','OPEN_DEBT','OPEN_TRANSACTION'],card:{lead:'text:MA_CONG_NO',title:'MA_CONG_NO',sub:['MA_GIAO_DICH','GHI_CHU'],amount:'SO_TIEN_PHAN_BO',date:'NGAY_PHAN_BO'},metrics:[{l:'Tổng phân bổ',sum:'SO_TIEN_PHAN_BO'},{l:'Số bút toán',count:1}]},
 CHUNG_TU:{dateField:'NGAY_CHUNG_TU',filters:['LOAI_BAN_GHI','LOAI_CHUNG_TU'],actions:['VIEW','CREATE','EDIT','OPEN_FILE','REPLACE_FILE','UNLINK'],card:{lead:'text:LOAI_CHUNG_TU',title:'TEN_FILE',sub:['SO_CHUNG_TU','MA_BAN_GHI'],date:'NGAY_CHUNG_TU'},metrics:[{l:'Tổng chứng từ',count:1},{l:'Thiếu tệp',count:1,where:{URL_FILE:''}},{l:'Có tệp',diff:[0,1]}]},
 PHE_DUYET:{dateField:'THOI_GIAN',filters:['LOAI_BAN_GHI','QUYET_DINH','EMAIL_NGUOI_DUYET'],actions:['VIEW','OPEN_SOURCE'],card:{lead:'text:QUYET_DINH',title:'MA_BAN_GHI',sub:['LOAI_BAN_GHI','EMAIL_NGUOI_DUYET'],date:'THOI_GIAN',status:'TRANG_THAI_SAU'},metrics:[{l:'Duyệt',count:1,where:{QUYET_DINH:'APPROVE'}},{l:'Từ chối',count:1,where:{QUYET_DINH:'REJECT'}},{l:'Trình duyệt',count:1,where:{QUYET_DINH:'SUBMIT'}},{l:'Tổng',count:1}]},
 DANH_MUC:{filters:['LOAI_DANH_MUC','TRANG_THAI'],actions:['VIEW','CREATE','EDIT','DUPLICATE','TOGGLE'],card:{lead:'bank:MA',title:'TEN',sub:['LOAI_DANH_MUC','MA']},metrics:[{l:'Tổng mục',count:1},{l:'Hoạt động',count:1,where:{TRANG_THAI:'HOAT_DONG'}},{l:'Ngừng',count:1,where:{TRANG_THAI:'NGUNG_HOAT_DONG'}}]},
 NGUOI_DUNG:{filters:['VAI_TRO','TRANG_THAI'],actions:['VIEW','CREATE','EDIT','TOGGLE'],card:{lead:'text:HO_TEN',title:'HO_TEN',sub:['EMAIL','VAI_TRO']},metrics:[{l:'Người dùng',count:1},{l:'Hoạt động',count:1,where:{TRANG_THAI:'HOAT_DONG'}},{l:'Quản trị',count:1,where:{VAI_TRO:'ADMIN'}}]},
 NHAT_KY:{dateField:'THOI_GIAN',filters:['EMAIL_NGUOI_DUNG','CHUC_NANG','HANH_DONG'],actions:['VIEW','OPEN_SOURCE'],card:{lead:'text:HANH_DONG',title:'MA_BAN_GHI',sub:['CHUC_NANG','EMAIL_NGUOI_DUNG'],date:'THOI_GIAN',status:'HANH_DONG'},metrics:[{l:'Tổng bản ghi',count:1}]}
});

/* V5.9.2: khóa cache khởi động; cache 30 phút (trước 6 giờ) để đổi vai trò trong sheet được nhận sớm */
const BOOT_KEY_='BOOT_V594_';
function getBootstrapData(){
 const user=getCurrentUser_(),cache=CacheService.getScriptCache(),key=BOOT_KEY_+String(user.email||user.role),hit=cacheGetJson_(cache,key);if(hit)return hit;
 const modules={};Object.keys(APP_MODULES).forEach(function(k){const c=APP_MODULES[k];if(c.adminOnly&&user.role!=='ADMIN')return;modules[k]=moduleConfigMeta_(c);});
 const out={version:'5.9.4',title:APP_CONFIG.title,user:user,permissions:ROLE_RULES[user.role]||ROLE_RULES.VIEWER,modules:modules,uiModules:UI_MODULES,lookups:{}};cachePutJson_(cache,key,out,1800);return out;
}
function moduleConfigMeta_(c){const hidden=['NGUOI_TAO','TAO_LUC','CAP_NHAT_LUC'].concat(c.calculated||[]),headers=[],add=function(a){(a||[]).forEach(function(x){if(x&&headers.indexOf(x)<0)headers.push(x);});};add([c.idField]);add(c.columns);add(c.required);add(c.dates);add(c.amounts);add(c.percents);add(Object.keys(c.enums||{}));return{title:c.title,group:c.group,idField:c.idField,headers:headers,fields:headers.filter(function(f){return f!==c.idField&&hidden.indexOf(f)<0;}),required:c.required||[],hidden:hidden,enums:c.enums||{},dates:c.dates||[],amounts:c.amounts||[],percents:c.percents||[],columns:c.columns||headers.slice(0,8),readOnly:!!c.readOnly,manualId:!!c.manualId,count:0,rows:[]};}
function readModuleMeta_(ss,key,c){const sh=requireSheet_(ss,key),physical=getHeaders_(sh),h=physical.concat((c.virtual||[]).filter(function(f){return physical.indexOf(f)<0;})),hidden=['NGUOI_TAO','TAO_LUC','CAP_NHAT_LUC'].concat(c.calculated||[]);ensureRequiredHeaders_(key,physical);return{title:c.title,group:c.group,idField:c.idField,headers:h,fields:h.filter(function(f){return f!==c.idField&&hidden.indexOf(f)<0;}),required:c.required||[],hidden:hidden,enums:c.enums||{},dates:c.dates||[],amounts:c.amounts||[],percents:c.percents||[],columns:(c.columns||h.slice(0,8)).filter(function(f){return h.indexOf(f)>=0;}),readOnly:!!c.readOnly,manualId:!!c.manualId,count:Math.max(0,sh.getLastRow()-1)};}
function buildBootstrapLookups_(ss,user){const keys=['TAI_KHOAN','KHOAN_VAY','NGUON_VON','KE_HOACH_THU_CHI','LICH_TRA_NO','CONG_NO','DANH_MUC'],rows={};keys.forEach(function(k){const c=APP_MODULES[k];if(c&&(!c.adminOnly||user.role==='ADMIN'))rows[k]=readSheet_(ss,k,c).rows;});return buildLookups_(rows);}
function cacheGetJson_(cache,key){try{const raw=cache.get(key);if(!raw)return null;const head=JSON.parse(raw);if(!head||!head.__chunks)return head;const keys=[];for(let i=0;i<head.__chunks;i++)keys.push(key+'__'+i);const parts=cache.getAll(keys);let text='';for(let i=0;i<keys.length;i++){const part=parts[keys[i]];if(part==null)return null;text+=part;}return JSON.parse(text);}catch(e){return null;}}
function cachePutJson_(cache,key,value,ttl){try{const text=JSON.stringify(value),size=24000;if(text.length<=size){cache.put(key,text,ttl);return true;}const count=Math.ceil(text.length/size);if(count>200)return false;const all={};for(let i=0;i<count;i++)all[key+'__'+i]=text.slice(i*size,(i+1)*size);cache.putAll(all,ttl);cache.put(key,JSON.stringify({__chunks:count}),ttl);return true;}catch(e){return false;}}/* V5.9: mảnh 24.000 ký tự (≤100KB kể cả chữ có dấu), ghi 1 lần */
function cacheRemoveJson_(cache,key){try{const raw=cache.get(key),head=raw?JSON.parse(raw):null;cache.remove(key);if(head&&head.__chunks)for(let i=0;i<head.__chunks;i++)cache.remove(key+'__'+i);}catch(e){try{cache.remove(key);}catch(ignore){}}}
function readSheetCached_(ss,key,c){const started=Date.now(),cache=CacheService.getScriptCache(),ck='DATA_V593_'+key,hit=cacheGetJson_(cache,ck);if(hit){hit._cacheHit=true;hit._loadMs=Date.now()-started;return hit;}const d=readSheet_(ss,key,c),stored={meta:d.meta,rows:d.rows};if(cachePutJson_(cache,ck,stored,DATA_TTL_))cache.put('DVER_'+key,String(Date.now()),DATA_TTL_);d._cacheHit=false;d._loadMs=Date.now()-started;return d;}
function invalidateModuleCache_(key){try{const cache=CacheService.getScriptCache();cacheRemoveJson_(cache,'DATA_V593_'+key);cache.remove('DVER_'+key);}catch(e){}}
/** V5.9.2: sửa / khóa / đổi vai trò người dùng qua app → xóa cache quyền và cache khởi động của email đó để có hiệu lực ngay. */
function invalidateUserCache_(email){try{const cache=CacheService.getScriptCache(),e=String(email||'').trim();if(!e)return;[e,e.toLowerCase()].filter(function(x,i,a){return a.indexOf(x)===i;}).forEach(function(x){cacheRemoveJson_(cache,'USER_V51_'+x);cacheRemoveJson_(cache,BOOT_KEY_+x);});}catch(err){}}
function getLookupData(moduleKey){const c=getModule_(moduleKey),ss=openFinanceSpreadsheet_(),map={MA_TAI_KHOAN:'TAI_KHOAN',MA_TAI_KHOAN_NGUON:'TAI_KHOAN',MA_TAI_KHOAN_DICH:'TAI_KHOAN',MA_KHOAN_VAY:'KHOAN_VAY',MA_NGUON_VON:'NGUON_VON',MA_KE_HOACH:'KE_HOACH_THU_CHI',MA_KE_HOACH_LIEN_QUAN:'KE_HOACH_THU_CHI',MA_LICH_TRA:'LICH_TRA_NO',MA_CONG_NO:'CONG_NO',MA_GIAO_DICH:'GIAO_DICH_TIEN',MA_DOI_TAC:'DANH_MUC'},targets={},rows={};requireSheet_(ss,moduleKey);(readModuleMeta_(ss,moduleKey,c).headers||[]).forEach(function(f){if(map[f])targets[map[f]]=true;});Object.keys(targets).forEach(function(k){rows[k]=readSheetCached_(ss,k,APP_MODULES[k]).rows;});return buildLookups_(rows);}
/* ============================ V5.9 · TẢI NHANH ============================
 * Trình duyệt giữ toàn bộ dữ liệu từng phân hệ (trừ Nhật ký) và tự lọc/tìm/chia trang.
 * getModuleData(k, ver): nếu dữ liệu không đổi (so dấu phiên bản DVER_) chỉ trả {same:true} – không mở bảng tính, không gửi dòng.
 * mutateAndFetch: ghi dữ liệu + trả luôn dữ liệu mới của phân hệ đang xem (1 lần gọi thay vì 2).
 * ======================================================================== */
const DATA_TTL_=1800;
const SERVER_PAGED_=Object.freeze({NHAT_KY:true});
function moduleDeps_(k,rows){const c=getModule_(k),deps=[k];if(k==='LICH_TRA_NO')deps.push('KHOAN_VAY','PHAN_BO_TRA_NO');Object.keys(BANK_REFS_).forEach(function(f){const src=BANK_REFS_[f];if(f!==c.idField&&deps.indexOf(src)<0&&(!rows||rows.some(function(r){return r[f];})))deps.push(src);});return deps;}
/* Dấu phiên bản = "MODULE:thời điểm cache" của phân hệ và các bảng nó tham chiếu; thiếu bất kỳ dấu nào → coi như đã đổi */
function dataVersion_(cache,deps){const got=cache.getAll(deps.map(function(d){return 'DVER_'+d;}));const out=[];for(let i=0;i<deps.length;i++){const v=got['DVER_'+deps[i]];if(!v)return '';out.push(deps[i]+':'+v);}return out.join('|');}
function getModuleData(moduleKey,knownVer,force){
 const started=Date.now(),c=getModule_(moduleKey),ss=openFinanceSpreadsheet_(),u=getCurrentUser_(ss);if(c.adminOnly&&u.role!=='ADMIN')throw new Error('Không có quyền xem phân hệ này.');
 if(SERVER_PAGED_[moduleKey])throw new Error('Phân hệ này tải theo trang.');
 const cache=CacheService.getScriptCache();
 if(force)moduleDeps_(moduleKey,null).forEach(invalidateModuleCache_);
 else if(knownVer){const deps=String(knownVer).split('|').map(function(x){return x.split(':')[0];});if(deps[0]===moduleKey&&deps.every(function(d){return !!APP_MODULES[d];})){const v=dataVersion_(cache,deps);if(v&&v===String(knownVer))return{module:moduleKey,same:true,ver:v,performance:{serverMs:Date.now()-started}};}}
 const d=readSheetCached_(ss,moduleKey,c);let rows=moduleKey==='LICH_TRA_NO'?enrichDebtScheduleRows_(ss,d.rows):d.rows;rows=enrichBankRefs_(ss,moduleKey,c,rows);
 return{module:moduleKey,meta:d.meta,rows:rows,ver:dataVersion_(cache,moduleDeps_(moduleKey,d.rows)),performance:{serverMs:Date.now()-started,cacheHit:!!d._cacheHit}};
}
function mutateAndFetch(fn,args,moduleKey){
 const allowed={saveRecord:saveRecord,deleteRecord:deleteRecord,transitionRecord:transitionRecord,copyMonthlySchedules:copyMonthlySchedules,importSchedules:importSchedules,syncLoanBalances:syncLoanBalances};
 if(!Object.prototype.hasOwnProperty.call(allowed,fn))throw new Error('Thao tác không hợp lệ.');
 const result=allowed[fn].apply(null,args||[]);
 let data=null;try{if(moduleKey&&APP_MODULES[moduleKey]&&!SERVER_PAGED_[moduleKey])data=getModuleData(moduleKey,'',false);}catch(e){}
 return{result:result,data:data};
}
function getAllLookups(){const ss=openFinanceSpreadsheet_(),targets={},rows={};['TAI_KHOAN','KHOAN_VAY','NGUON_VON','KE_HOACH_THU_CHI','LICH_TRA_NO','CONG_NO','GIAO_DICH_TIEN','DANH_MUC'].forEach(function(k){if(APP_MODULES[k])targets[k]=true;});Object.keys(targets).forEach(function(k){try{rows[k]=readSheetCached_(ss,k,APP_MODULES[k]).rows;}catch(e){rows[k]=[];}});return buildLookups_(rows);}
function listRecords(moduleKey,filters,sort,page,pageSize){
 const started=Date.now(),c=getModule_(moduleKey),ss=openFinanceSpreadsheet_(),u=getCurrentUser_(ss);if(c.adminOnly&&u.role!=='ADMIN')throw new Error('Không có quyền xem phân hệ này.');
 const cfg=UI_MODULES[moduleKey]||{},d=readSheetCached_(ss,moduleKey,c),f=filters||{},q=String(f.q||'').toLocaleLowerCase('vi'),dateField=String(f.dateField||cfg.dateField||''),exact=f.exact||{},sourceRows=moduleKey==='LICH_TRA_NO'?enrichDebtScheduleRows_(ss,d.rows):d.rows;
 let rows=sourceRows.filter(function(r){
  if(q&&!Object.keys(r).some(function(h){return String(r[h]==null?'':r[h]).toLocaleLowerCase('vi').indexOf(q)>=0;}))return false;
  if(f.status&&f.status!=='ALL'&&String(r.TRANG_THAI||'')!==String(f.status))return false;
  if(Object.keys(exact).some(function(k){return exact[k]&&exact[k]!=='ALL'&&String(r[k]||'')!==String(exact[k]);}))return false;
  if(dateField&&(r[dateField]||(cfg.fallbackDateField&&r[cfg.fallbackDateField]))){const v=String(r[dateField]||r[cfg.fallbackDateField]).slice(0,10),y=+v.slice(0,4),m=+v.slice(5,7);if(f.year&&+f.year!==y)return false;if(f.month&&+f.month!==m)return false;if(f.dateFrom&&v<String(f.dateFrom))return false;if(f.dateTo&&v>String(f.dateTo))return false;}else if(cfg.periodField&&r[cfg.periodField]){const pv=String(r[cfg.periodField]),parts=pv.match(/(\d{4})[-\/]?(\d{1,2})?/),y=parts?+parts[1]:0,m=parts&&parts[2]?+parts[2]:0;if(f.year&&+f.year!==y)return false;if(f.month&&m&&+f.month!==m)return false;}
  return true;
 });
 const sf=sort&&sort.field,dir=sort&&String(sort.direction).toLowerCase()==='desc'?-1:1;if(!sf&&moduleKey==='NHAT_KY')rows.sort(function(a,b){return String(b.THOI_GIAN||'').localeCompare(String(a.THOI_GIAN||''));});/* V5.9.3: Nhật ký mới nhất lên đầu */if(!sf&&cfg.monthNav)rows.sort(function(a,b){return String(a.NGAY_DEN_HAN||'').localeCompare(String(b.NGAY_DEN_HAN||''))||String(a.MA_KHOAN_VAY||'').localeCompare(String(b.MA_KHOAN_VAY||''));});if(sf&&d.meta.headers.indexOf(sf)>=0)rows.sort(function(a,b){const x=a[sf],y=b[sf];if(x===y)return 0;return(x==null||x==='')?-dir:(y==null||y==='')?dir:(x>y?dir:-dir);});
 const total=rows.length,ps=cfg.noPaging?Math.max(1,total):Math.min(200,Math.max(10,+pageSize||25)),pg=cfg.noPaging?1:Math.max(1,+page||1),start=(pg-1)*ps,totals={};(c.amounts||[]).forEach(function(k){totals[k]=rows.reduce(function(n,r){return n+(Number(r[k])||0);},0);});
 const pageRows=enrichBankRefs_(ss,moduleKey,c,rows.slice(start,start+ps));
 return{module:moduleKey,meta:d.meta,rows:pageRows,total:total,page:pg,pageSize:ps,pages:Math.max(1,Math.ceil(total/ps)),totals:totals,metrics:computeMetrics_(rows,cfg.metrics),months:cfg.monthNav?monthCounts_(sourceRows):undefined,filters:f,performance:{serverMs:Date.now()-started,sourceMs:d._loadMs||0,cacheHit:!!d._cacheHit}};
}
/** Chỉ số tổng theo UI_MODULES.metrics — tính trên TOÀN BỘ kết quả đã lọc (không theo trang).
 *  sum: 1 trường hoặc mảng trường · count · diff/add: theo chỉ số trước · firstBy/lastBy: lấy giá trị dòng đầu/cuối của từng nhóm (vd. dư nợ đầu kỳ / sau khi trả theo từng khoản vay) rồi cộng. */
/** V5.7.3: danh sách tháng có kỳ trả + số kỳ mỗi tháng (bỏ kỳ HUY) – dùng cho thanh chọn tháng của Lịch trả nợ. */
function monthCounts_(rows){const m={};(rows||[]).forEach(function(r){const p=periodKey_(r.NGAY_DEN_HAN);if(p&&String(r.TRANG_THAI)!=='HUY')m[p]=(m[p]||0)+1;});return Object.keys(m).sort().map(function(p){return[p,m[p]];});}
function computeMetrics_(rows,specs){
 if(!specs||!specs.length)return null;
 const match=function(r,cond,neg){if(!cond)return true;return Object.keys(cond).every(function(k){const want=[].concat(cond[k]).map(String),hit=want.indexOf(String(r[k]==null?'':r[k]))>=0;return neg?!hit:hit;});};
 const out=[];
 specs.forEach(function(m){
  let value=0,isMoney=false;
  if(m.diff){value=(out[m.diff[0]]?out[m.diff[0]].value:0)-(out[m.diff[1]]?out[m.diff[1]].value:0);isMoney=!!(out[m.diff[0]]&&out[m.diff[0]].money);}
  else if(m.add){value=m.add.reduce(function(n,i){return n+(out[i]?out[i].value:0);},0);isMoney=m.add.some(function(i){return out[i]&&out[i].money;});}
  else{const list=rows.filter(function(r){return match(r,m.where,false)&&(!m.not||match(r,m.not,true));});
   if(m.firstBy||m.lastBy){const o=m.firstBy||m.lastBy,last=!!m.lastBy,pick={};list.forEach(function(r){const g=String(r[o.group]==null?'':r[o.group]),k=String(r[o.order]==null?'':r[o.order]);if(!Object.prototype.hasOwnProperty.call(pick,g)||(last?k>=pick[g].k:k<pick[g].k))pick[g]={k:k,v:Number(r[o.field])||0};});value=Object.keys(pick).reduce(function(n,g){return n+pick[g].v;},0);isMoney=true;}
   else if(m.sum){const fs=[].concat(m.sum);value=list.reduce(function(n,r){return fs.reduce(function(x,f){return x+(Number(r[f])||0);},n);},0);isMoney=true;}else value=list.length;}
  out.push({label:m.l,value:value,money:isMoney});
 });
 return out;
}
/** V5.6: gắn mã ngân hàng cho các trường tham chiếu (khoản vay, tài khoản) để giao diện hiện logo chuẩn mà không cần tải trước phân hệ nguồn. Chỉ xử lý các dòng của trang hiện tại. */
const BANK_REFS_=Object.freeze({MA_KHOAN_VAY:'KHOAN_VAY',MA_TAI_KHOAN:'TAI_KHOAN',MA_TAI_KHOAN_NGUON:'TAI_KHOAN',MA_TAI_KHOAN_DICH:'TAI_KHOAN'});
function enrichBankRefs_(ss,moduleKey,c,pageRows){
 const fields=Object.keys(BANK_REFS_).filter(function(f){return f!==c.idField&&pageRows.some(function(r){return r[f];});});
 if(!fields.length)return pageRows;
 const maps={};
 fields.forEach(function(f){const src=BANK_REFS_[f];if(maps[src])return;const sc=APP_MODULES[src],m={};try{readSheetCached_(ss,src,sc).rows.forEach(function(x){m[String(x[sc.idField]||'')]=x;});}catch(e){}maps[src]=m;});
 return pageRows.map(function(r){
  const o=Object.assign({},r);
  fields.forEach(function(f){const ref=maps[BANK_REFS_[f]][String(r[f]||'')];if(!ref)return;o['_NH_'+f]=ref.MA_NGAN_HANG||'';if(f==='MA_KHOAN_VAY'){o._TEN_KHOAN_VAY=ref.TEN_KHOAN_VAY||'';o._SO_HOP_DONG=ref.SO_HOP_DONG||'';o._CONG_TY_VAY=ref.MA_CONG_TY_VAY||'';}if(BANK_REFS_[f]==='TAI_KHOAN')o['_TEN_'+f]=ref.TEN_TAI_KHOAN||'';});
  return o;
 });
}
/** Dư nợ từng kỳ (V5.7.2 – phương án ③, tính theo GỐC PHẢI TRẢ):
 *  Điểm xuất phát cố định = DU_NO_GOC_BAN_DAU (chưa có thì DU_NO_GOC_DAU_KY → TONG_GOC_GIAI_NGAN → HAN_MUC_VAY; số 0 vẫn là 0).
 *  Mỗi kỳ trừ GOC_PHAI_TRA (kế hoạch). Không trừ kỳ HUY và kỳ đến hạn ≤ NGAY_GOC_BAN_DAU (đã nằm trong số gốc ban đầu).
 *  Vì không phụ thuộc DU_NO_GOC_DAU_KY (cột được đồng bộ ghi vào) nên đồng bộ nhiều lần không trừ gốc 2 lần. */
function hasNum_(v){return v!==''&&v!=null&&isFinite(Number(v));}
function loanBase_(l){const k=['DU_NO_GOC_BAN_DAU','DU_NO_GOC_DAU_KY','TONG_GOC_GIAI_NGAN','HAN_MUC_VAY'].find(function(f){return hasNum_(l[f]);});return k?Number(l[k]):0;}
function loanBaseDate_(l){return hasNum_(l.DU_NO_GOC_BAN_DAU)?dayKey_(l.NGAY_GOC_BAN_DAU):'';}
function dayKey_(v){return String(v==null?'':v).slice(0,10);}
function enrichDebtScheduleRows_(ss,rows){const loans=readSheetCached_(ss,'KHOAN_VAY',APP_MODULES.KHOAN_VAY).rows,allocations=readSheetCached_(ss,'PHAN_BO_TRA_NO',APP_MODULES.PHAN_BO_TRA_NO).rows,loanMap={},paidMap={};loans.forEach(function(x){loanMap[String(x.MA_KHOAN_VAY||'')]=x;});allocations.forEach(function(x){const key=String(x.MA_LICH_TRA||'');paidMap[key]=(paidMap[key]||0)+(Number(x.GOC_DA_TRA)||0)+(Number(x.LAI_DA_TRA)||0)+(Number(x.PHI_DA_TRA)||0);});const groups={};(rows||[]).forEach(function(x){const key=String(x.MA_KHOAN_VAY||'');(groups[key]||(groups[key]=[])).push(Object.assign({},x));});const out=[];Object.keys(groups).forEach(function(key){const loan=loanMap[key]||{},items=groups[key],from=loanBaseDate_(loan);items.sort(function(a,b){return String(a.NGAY_DEN_HAN||'').localeCompare(String(b.NGAY_DEN_HAN||''));});let balance=loanBase_(loan);items.forEach(function(x){const explicit=x.TONG_DU_NO!==''&&x.TONG_DU_NO!=null?Number(x.TONG_DU_NO):NaN,before=isFinite(explicit)?explicit:balance,skip=String(x.TRANG_THAI)==='HUY'||(from&&dayKey_(x.NGAY_DEN_HAN)<=from),principal=skip?0:Math.max(0,Number(x.GOC_PHAI_TRA)||0),after=Math.max(0,before-principal);x.TONG_DU_NO=before;x.DU_NO_SAU_KHI_TRA=after;x.TONG_DA_THANH_TOAN=paidMap[String(x.MA_LICH_TRA||'')]||0;balance=after;out.push(x);});});return out;}
function getInitialAppData(moduleKey,filters,sort,page,pageSize){const started=Date.now(),bootstrap=getBootstrapData(),preferred=bootstrap.modules[moduleKey]?moduleKey:(bootstrap.modules.LICH_TRA_NO?'LICH_TRA_NO':Object.keys(bootstrap.modules)[0]),local=!SERVER_PAGED_[preferred];return{bootstrap:bootstrap,module:preferred,data:local?getModuleData(preferred,'',false):null,result:local?null:listRecords(preferred,filters,sort,page,pageSize),performance:{serverMs:Date.now()-started}};}
function getRecordDetail(moduleKey,recordId){const c=getModule_(moduleKey),ss=openFinanceSpreadsheet_(),u=getCurrentUser_(ss);if(c.adminOnly&&u.role!=='ADMIN')throw new Error('Không có quyền xem phân hệ này.');const sh=requireSheet_(ss,moduleKey),h=getHeaders_(sh),found=findRowById_(sh,h,c.idField,String(recordId||''));if(!found)throw new Error('Không tìm thấy bản ghi.');const row={};h.forEach(function(k,i){row[k]=serializeCell_(found.values[i],k);});return{record:row,ui:UI_MODULES[moduleKey]||{},meta:readModuleMeta_(ss,moduleKey,c)};}
function getMonthlyScheduleCopyPreview(sourcePeriod,targetPeriod){const source=parsePeriod_(sourcePeriod),target=parsePeriod_(targetPeriod);if(source.key===target.key)throw new Error('Tháng mới phải khác tháng nguồn.');const ss=openFinanceSpreadsheet_(),c=APP_MODULES.LICH_TRA_NO,u=getCurrentUser_(ss),schedules=readSheet_(ss,'LICH_TRA_NO',c).rows,loans=readSheetCached_(ss,'KHOAN_VAY',APP_MODULES.KHOAN_VAY).rows,loanMap={};loans.forEach(function(x){loanMap[String(x.MA_KHOAN_VAY)]=x;});const targetKeys={};schedules.forEach(function(x){if(periodKey_(x.NGAY_DEN_HAN)===target.key)targetKeys[String(x.MA_KHOAN_VAY)+'|'+target.key]=true;});const rows=schedules.filter(function(x){return periodKey_(x.NGAY_DEN_HAN)===source.key&&String(x.TRANG_THAI||'')!=='HUY';}).map(function(x){const loan=loanMap[String(x.MA_KHOAN_VAY)]||{},newDate=moveDateToPeriod_(x.NGAY_DEN_HAN,target);return{sourceId:x.MA_LICH_TRA,loanId:x.MA_KHOAN_VAY,loanName:loan.TEN_KHOAN_VAY||loan.SO_HOP_DONG||x.MA_KHOAN_VAY,bank:loan.MA_NGAN_HANG||'',contract:loan.SO_HOP_DONG||'',oldDate:String(x.NGAY_DEN_HAN||''),newDate:Utilities.formatDate(newDate,APP_CONFIG.timeZone,'yyyy-MM-dd'),principal:Number(x.GOC_PHAI_TRA)||0,interest:Number(x.LAI_PHAI_TRA)||0,fee:Number(x.PHI_PHAI_TRA)||0,adjustment:Number(x.DIEU_CHINH_TANG_GIAM)||0,duplicate:!!targetKeys[String(x.MA_KHOAN_VAY)+'|'+target.key]};});return{sourcePeriod:source.key,targetPeriod:target.key,rows:rows,user:u};}
function copyMonthlySchedules(sourcePeriod,targetPeriod,sourceIds,options){const source=parsePeriod_(sourcePeriod),target=parsePeriod_(targetPeriod),ids=(sourceIds||[]).map(String).filter(Boolean),opts=options||{};if(source.key===target.key)throw new Error('Tháng mới phải khác tháng nguồn.');if(!ids.length)throw new Error('Vui lòng chọn ít nhất một khoản nợ.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=openFinanceSpreadsheet_(),c=APP_MODULES.LICH_TRA_NO,u=requirePermission_(ss,'write',c),sh=requireSheet_(ss,'LICH_TRA_NO'),h=getHeaders_(sh),values=sh.getDataRange().getValues(),idIndex=h.indexOf(c.idField),loanIndex=h.indexOf('MA_KHOAN_VAY'),dateIndex=h.indexOf('NGAY_DEN_HAN'),selected={};ids.forEach(function(x){selected[x]=true;});const existing={};values.slice(1).forEach(function(r){if(periodKey_(r[dateIndex])===target.key)existing[String(r[loanIndex])+'|'+target.key]=true;});const now=new Date(),created=[],skipped=[],out=[];values.slice(1).forEach(function(row){const sourceId=String(row[idIndex]||'');if(!selected[sourceId]||periodKey_(row[dateIndex])!==source.key)return;const key=String(row[loanIndex])+'|'+target.key;if(existing[key]){skipped.push(sourceId);return;}const copy=row.slice();copy[idIndex]=makeId_('LICH_TRA_NO');copy[dateIndex]=moveDateToPeriod_(row[dateIndex],target);setIfHeader_(copy,h,'KY_TRA_NO',target.key);setIfHeader_(copy,h,'TRANG_THAI','DU_KIEN');if(opts.keepDetails===false){setIfHeader_(copy,h,'GHI_CHU','');setIfHeader_(copy,h,'MA_TAI_KHOAN_CHI','');}setIfHeader_(copy,h,'NGUOI_TAO',u.email);setIfHeader_(copy,h,'TAO_LUC',now);setIfHeader_(copy,h,'CAP_NHAT_LUC',now);protectFormulaText_(copy,h,c);out.push(copy);created.push(copy[idIndex]);existing[key]=true;});if(out.length)sh.getRange(sh.getLastRow()+1,1,out.length,h.length).setValues(out);SpreadsheetApp.flush();writeAudit_(ss,'LICH_TRA_NO',target.key,'TAO_DU_LIEU_THANG','Nguồn '+source.key+'; tạo '+created.length+'; bỏ qua trùng '+skipped.length);invalidateModuleCache_('LICH_TRA_NO');return{ok:true,created:created.length,skipped:skipped.length,ids:created};}finally{lock.releaseLock();}}
function transitionRecord(moduleKey,recordId,action,payload){const lock=LockService.getScriptLock();lock.waitLock(30000);try{
 const c=getModule_(moduleKey),id=String(recordId||'').trim(),a=String(action||'').toUpperCase(),data=payload||{},ss=openFinanceSpreadsheet_(),u=requirePermission_(ss,a==='APPROVE'||a==='REJECT'?'approve':a==='CANCEL'?'remove':'write',c),sh=requireSheet_(ss,moduleKey),h=getHeaders_(sh),found=findRowById_(sh,h,c.idField,id),si=h.indexOf('TRANG_THAI');
 if(!found)throw new Error('Không tìm thấy bản ghi.');if(si<0)throw new Error('Phân hệ không có trạng thái nghiệp vụ.');const allowed=(c.enums||{}).TRANG_THAI||[],before=String(found.values[si]||''),validFrom={SUBMIT:['NHAP','DU_KIEN','MOI'],APPROVE:['CHO_DUYET'],REJECT:['CHO_DUYET'],PAUSE:['DU_KIEN','DANG_VAY'],SETTLE:['DANG_VAY'],OVERDUE:['MOI','DEN_HAN','DU_KIEN']},cancel=cancellationStatus_(c),targets={SUBMIT:'CHO_DUYET',APPROVE:'DA_DUYET',REJECT:cancel||'HUY',CANCEL:cancel||'HUY',COMPLETE:allowed.indexOf('DA_THUC_HIEN')>=0?'DA_THUC_HIEN':allowed.indexOf('HOAN_THANH')>=0?'HOAN_THANH':allowed.indexOf('DA_THANH_TOAN')>=0?'DA_THANH_TOAN':'',PAUSE:'TAM_DUNG',SETTLE:'DA_TAT_TOAN',OVERDUE:'QUA_HAN'};let after=targets[a];/* V5.9.2: let – TOGGLE gán lại bên dưới (const gây lỗi "Assignment to constant variable") */
 if(validFrom[a]&&validFrom[a].indexOf(before)<0)throw new Error('Không thể '+a.toLowerCase()+' khi bản ghi đang ở trạng thái '+before+'.');if(a==='CANCEL'&&/HUY|DA_THANH_TOAN|HOAN_THANH|DA_TAT_TOAN/.test(before))throw new Error('Bản ghi đã ở trạng thái kết thúc.');if(a==='TOGGLE')after=/NGUNG|TAM_DUNG/.test(before)?(allowed.indexOf('HOAT_DONG')>=0?'HOAT_DONG':allowed[0]):(allowed.indexOf('NGUNG_HOAT_DONG')>=0?'NGUNG_HOAT_DONG':allowed.indexOf('TAM_DUNG')>=0?'TAM_DUNG':'');
 if(!after||allowed.indexOf(after)<0)throw new Error('Tác vụ không hợp lệ với trạng thái của phân hệ.');if((a==='REJECT'||a==='CANCEL')&&!String(data.reason||'').trim())throw new Error('Vui lòng nhập lý do.');
 found.values[si]=after;setIfHeader_(found.values,h,'CAP_NHAT_LUC',new Date());sh.getRange(found.row,1,1,h.length).setValues([found.values]);if(a==='APPROVE'||a==='REJECT'||a==='SUBMIT')appendApproval_(ss,moduleKey,id,before,after,a,String(data.reason||''),u.email);writeAudit_(ss,moduleKey,id,a,before+' → '+after+(data.reason?' | '+data.reason:''));invalidateModuleCache_(moduleKey);if(moduleKey==='NGUOI_DUNG')invalidateUserCache_(id);return{ok:true,status:after};
}finally{lock.releaseLock();}}


/* ======================= V5.7.2 · ĐỒNG BỘ DƯ NỢ KHOẢN VAY (phương án ③, tính theo GỐC PHẢI TRẢ) ======================= */
/** Tạo/điền cột DU_NO_GOC_BAN_DAU + NGAY_GOC_BAN_DAU cho Khoản vay: ô trống lấy DU_NO_GOC_DAU_KY và NGAY_CHOT_DU_NO_DAU_KY hiện tại (hoặc TONG_GOC_GIAI_NGAN). Chỉ ghi ô trống. */
function migrateLoanBase_(ss){const c=APP_MODULES.KHOAN_VAY,sh=requireSheet_(ss,'KHOAN_VAY');ensureAutoColumns_(sh,c);const v=sh.getDataRange().getValues(),h=v[0].map(function(x){return String(x).trim();}),bi=h.indexOf('DU_NO_GOC_BAN_DAU'),di=h.indexOf('DU_NO_GOC_DAU_KY'),gi=h.indexOf('TONG_GOC_GIAI_NGAN'),ii=h.indexOf(c.idField),ni=h.indexOf('NGAY_GOC_BAN_DAU'),ci=h.indexOf('NGAY_CHOT_DU_NO_DAU_KY');let n=0;if(bi<0)return 0;for(let r=1;r<v.length;r++){if(!String(v[r][ii]||'').trim()||hasNum_(v[r][bi]))continue;const fromD=hasNum_(v[r][di]),val=fromD?Number(v[r][di]):hasNum_(v[r][gi])?Number(v[r][gi]):'';if(val==='')continue;sh.getRange(r+1,bi+1).setValue(val);if(fromD&&ni>=0&&ci>=0&&v[r][ci]!==''&&v[r][ni]==='')sh.getRange(r+1,ni+1).setValue(v[r][ci]);n++;}if(n){sh.getRange(2,bi+1,Math.max(1,sh.getMaxRows()-1),1).setNumberFormat('#,##0');invalidateModuleCache_('KHOAN_VAY');}return n;}
/** CHẠY 1 LẦN (tùy chọn) trong trình soạn Apps Script: tạo cột Dư nợ gốc ban đầu cho Khoản vay. Tác vụ Đồng bộ cũng tự làm bước này. */
function capNhatDataGoc_KhoanVay(){const ss=openFinanceSpreadsheet_(),lock=LockService.getScriptLock();lock.waitLock(30000);try{const n=migrateLoanBase_(ss),msg='Sheet KHOAN_VAY: cột DU_NO_GOC_BAN_DAU sẵn sàng, đã điền '+n+' dòng từ Dư nợ gốc đầu kỳ hiện tại.';writeAudit_(ss,'KHOAN_VAY','CAU_TRUC','CAP_NHAT_CAU_TRUC',msg);console.log(msg);return msg;}finally{lock.releaseLock();}}
/* ======================= V5.9.4 · GHI DƯ NỢ GỐC BAN ĐẦU TỪ BÁO CÁO GỐC LÃI T10/2026 ======================= */
/** Nguồn: file "BAO_CAO_GOC_LAI_T10.2026 - KE HOACH", sheet Tinh-T10.2026, cột "Dư nợ còn lại" (141 dòng).
 *  Mỗi khoản vay = tổng các dòng cùng Công ty + Ngân hàng trong file (đối chiếu: gốc và lãi kỳ 10/2026 khớp 88/88 khoản).
 *  Số dư là SAU kỳ trả tháng 9 (kiểm bằng lãi kỳ 9) → ngày gốc ban đầu 30/09/2026: Lịch trả nợ không trừ kỳ ≤ 30/09, bắt đầu trừ từ kỳ 10/2026.
 *  6 khoản không có trong file (KV-T9-019, 023, 054, 055, 058, 080) giữ nguyên. */
const DU_NO_GOC_T10_2026_={NGAY:'2026-09-30',SO:{'KV-T9-001':521365482671,'KV-T9-002':600281477368,'KV-T9-003':50000000000,'KV-T9-004':197606639788,'KV-T9-005':13988314780,'KV-T9-006':161283343483,'KV-T9-007':171149778386,'KV-T9-008':599352247049,'KV-T9-009':122162453043,'KV-T9-010':19999999799,'KV-T9-011':66178470740,'KV-T9-012':329666803094,'KV-T9-013':547150000000,'KV-T9-014':4997827967,'KV-T9-015':15000000000,'KV-T9-016':42256000000,'KV-T9-017':160000000000,'KV-T9-018':17999190000,'KV-T9-020':24995642110,'KV-T9-021':4470000000,'KV-T9-022':11500000000,'KV-T9-024':3150000000,'KV-T9-025':6000000000,'KV-T9-026':14200000000,'KV-T9-027':16743844000,'KV-T9-028':12900000000,'KV-T9-029':64960000000,'KV-T9-030':18000000000,'KV-T9-031':6000000000,'KV-T9-032':7000000000,'KV-T9-033':21991465800,'KV-T9-034':63500000000,'KV-T9-035':12209865000,'KV-T9-036':29506000000,'KV-T9-037':9816000000,'KV-T9-038':10884000000,'KV-T9-039':2614615389,'KV-T9-040':10565000000,'KV-T9-041':5805218686,'KV-T9-042':4483963820,'KV-T9-043':5000000000,'KV-T9-044':15760000000,'KV-T9-045':5380000000,'KV-T9-046':5081018854,'KV-T9-047':2366616096,'KV-T9-048':3528455702,'KV-T9-049':7270971092,'KV-T9-050':5167658656,'KV-T9-051':4682851302,'KV-T9-052':11035200000,'KV-T9-053':119849428111,'KV-T9-056':2887514000,'KV-T9-057':12512485000,'KV-T9-059':5888000000,'KV-T9-060':11775200000,'KV-T9-061':7109500000,'KV-T9-062':15525555553,'KV-T9-063':8635410000,'KV-T9-064':4712470000,'KV-T9-065':9850000000,'KV-T9-066':9900000000,'KV-T9-067':5347000000,'KV-T9-068':9443000000,'KV-T9-069':14958400000,'KV-T9-070':3211600000,'KV-T9-071':8145000000,'KV-T9-072':16290000000,'KV-T9-073':3766000000,'KV-T9-074':16160020000,'KV-T9-075':12929167000,'KV-T9-076':7533338000,'KV-T9-077':5000000000,'KV-T9-078':5000000000,'KV-T9-079':7840008000,'KV-T9-081':5950000000,'KV-T9-082':3000000000,'KV-T9-083':7000000000,'KV-T9-084':5993750000,'KV-T9-085':5803480000,'KV-T9-086':6006248000,'KV-T9-087':4305000000,'KV-T9-088':2000000000,'KV-T9-089':8433251000,'KV-T9-090':11790000000,'KV-T10-TAM-001':4700000000,'KV-T10-TAM-002':4000000000,'KV-T10-TAM-003':3600000000,'KV-T10-TAM-004':6800000000}};
function duNoGocT10Plan_(ss){const c=APP_MODULES.KHOAN_VAY,sh=requireSheet_(ss,'KHOAN_VAY');ensureAutoColumns_(sh,c);const v=sh.getDataRange().getValues(),h=v[0].map(function(x){return String(x).trim();}),ii=h.indexOf(c.idField),bi=h.indexOf('DU_NO_GOC_BAN_DAU'),ni=h.indexOf('NGAY_GOC_BAN_DAU');if(bi<0||ni<0)throw new Error('Sheet KHOAN_VAY thiếu cột DU_NO_GOC_BAN_DAU hoặc NGAY_GOC_BAN_DAU.');const so=DU_NO_GOC_T10_2026_.SO,seen={},changes=[];for(let r=1;r<v.length;r++){const id=String(v[r][ii]||'').trim();if(!Object.prototype.hasOwnProperty.call(so,id))continue;seen[id]=true;const old=v[r][bi],oldD=serializeCell_(v[r][ni],'NGAY_GOC_BAN_DAU');if(Number(old)===so[id]&&String(oldD).slice(0,10)===DU_NO_GOC_T10_2026_.NGAY)continue;changes.push({row:r+1,id:id,old:old,oldDate:oldD,nw:so[id]});}return{sh:sh,bi:bi,ni:ni,changes:changes,missing:Object.keys(so).filter(function(id){return !seen[id];})};}
/** BƯỚC 1 – XEM TRƯỚC (không ghi gì): Apps Script → chọn hàm xemTruoc_DuNoGocBanDau_T10 → Chạy → xem Nhật ký thực thi. */
function xemTruoc_DuNoGocBanDau_T10(){const p=duNoGocT10Plan_(openFinanceSpreadsheet_()),msg='Sẽ cập nhật '+p.changes.length+' khoản vay (ngày gốc ban đầu → 30/09/2026)'+(p.missing.length?'; KHÔNG tìm thấy mã: '+p.missing.join(', '):'')+'\n'+p.changes.map(function(x){return x.id+': '+Number(x.old||0).toLocaleString('vi-VN')+' → '+x.nw.toLocaleString('vi-VN');}).join('\n');console.log(msg);return msg;}
/** BƯỚC 2 – GHI (chạy 1 lần): chọn hàm capNhatDataGoc_DuNoGocBanDau_T10 → Chạy. Ghi DU_NO_GOC_BAN_DAU + NGAY_GOC_BAN_DAU cho 88 khoản vay, ghi Nhật ký.
 *  Chạy lại an toàn: khoản đã đúng thì bỏ qua. Sau đó vào Lịch trả nợ → ⟳ Đồng bộ dư nợ tháng 10/2026 để cập nhật Dư nợ gốc đầu kỳ. */
function capNhatDataGoc_DuNoGocBanDau_T10(){const ss=openFinanceSpreadsheet_(),lock=LockService.getScriptLock();lock.waitLock(30000);try{const p=duNoGocT10Plan_(ss),c=APP_MODULES.KHOAN_VAY,d=normalizeInput_(DU_NO_GOC_T10_2026_.NGAY,'NGAY_GOC_BAN_DAU',c);p.changes.forEach(function(x){p.sh.getRange(x.row,p.bi+1).setValue(x.nw);p.sh.getRange(x.row,p.ni+1).setValue(d);});if(p.changes.length){p.sh.getRange(2,p.bi+1,Math.max(1,p.sh.getMaxRows()-1),1).setNumberFormat('#,##0');SpreadsheetApp.flush();invalidateModuleCache_('KHOAN_VAY');invalidateModuleCache_('LICH_TRA_NO');}const msg='KHOAN_VAY: cập nhật Dư nợ gốc ban đầu '+p.changes.length+' khoản (ngày 30/09/2026, nguồn báo cáo gốc lãi T10/2026)'+(p.missing.length?'; không tìm thấy mã: '+p.missing.join(', '):'');writeAudit_(ss,'KHOAN_VAY','DU_NO_GOC_BAN_DAU','CAP_NHAT_DATA_GOC',msg+' | '+p.changes.map(function(x){return x.id+': '+x.old+' → '+x.nw;}).join('; '));console.log(msg);return msg;}finally{lock.releaseLock();}}
function periodLastDay_(period){const p=parsePeriod_(period);return Utilities.formatDate(new Date(p.year,p.month,0),APP_CONFIG.timeZone,'yyyy-MM-dd');}
/** Các tháng có kỳ trả (mới nhất trước) + tháng mặc định = tháng mới nhất không vượt quá tháng hiện tại. */
function debtSyncMonths_(sched){const set={};sched.forEach(function(r){const p=periodKey_(r.NGAY_DEN_HAN);if(p&&String(r.TRANG_THAI)!=='HUY')set[p]=true;});const months=Object.keys(set).sort().reverse(),now=Utilities.formatDate(new Date(),APP_CONFIG.timeZone,'yyyy-MM');return{months:months,latest:months.find(function(m){return m<=now;})||months[months.length-1]||''};}
/** Tính số đồng bộ cho tháng chốt: Dư nợ sau khi trả của KỲ CUỐI tháng đó (theo gốc phải trả) của từng khoản vay. */
function debtSyncCompute_(ss,period){
 const p=parsePeriod_(period).key,cutoff=periodLastDay_(p),loans=readSheet_(ss,'KHOAN_VAY',APP_MODULES.KHOAN_VAY).rows,sched=enrichDebtScheduleRows_(ss,readSheet_(ss,'LICH_TRA_NO',APP_MODULES.LICH_TRA_NO).rows);
 return loans.map(function(l){
  const id=String(l.MA_KHOAN_VAY),from=loanBaseDate_(l),mine=sched.filter(function(r){return String(r.MA_KHOAN_VAY)===id&&String(r.TRANG_THAI)!=='HUY';}),inMonth=mine.filter(function(r){return periodKey_(r.NGAY_DEN_HAN)===p;}),last=inMonth[inMonth.length-1];
  const upTo=mine.filter(function(r){const d=dayKey_(r.NGAY_DEN_HAN);return d<=cutoff&&(!from||d>from);}),plan=upTo.reduce(function(n,r){return n+(Number(r.GOC_PHAI_TRA)||0);},0),planMonth=inMonth.reduce(function(n,r){return n+(Number(r.GOC_PHAI_TRA)||0);},0);
  const cur=hasNum_(l.DU_NO_GOC_DAU_KY)?Number(l.DU_NO_GOC_DAU_KY):0,nw=last?Number(last.DU_NO_SAU_KHI_TRA)||0:0,cnt=function(re){return inMonth.filter(function(r){return re.test(String(r.TRANG_THAI));}).length;},w=[];
  if(cnt(/^QUA_HAN$/))w.push(['bad',cnt(/^QUA_HAN$/)+' kỳ quá hạn']);if(cnt(/^(DEN_HAN|DU_KIEN|DA_TRA_MOT_PHAN)$/))w.push(['warn',cnt(/^(DEN_HAN|DU_KIEN|DA_TRA_MOT_PHAN)$/)+' kỳ chưa trả đủ']);
  let skip='';if(l.TRANG_THAI==='DU_KIEN')skip='Dự kiến – chưa giải ngân';else if(l.TRANG_THAI==='DA_TAT_TOAN')skip='Đã tất toán';else if(!last)skip='Không có kỳ trả trong tháng '+p.split('-').reverse().join('/');else if(from&&cutoff<=from)skip='Tháng chốt không sau ngày gốc ban đầu '+from.split('-').reverse().join('/');
  if(!skip&&nw===0)w.push(['info','Đã trả hết – nên Tất toán']);
  return{id:id,name:l.TEN_KHOAN_VAY||id,bank:l.MA_NGAN_HANG||'',contract:l.SO_HOP_DONG||'',status:l.TRANG_THAI||'',base:loanBase_(l),plan:plan,planMonth:planMonth,lastId:last?last.MA_LICH_TRA:'',lastDate:last?dayKey_(last.NGAY_DEN_HAN):'',newBalance:nw,current:cur,diff:nw-cur,lastCutoff:dayKey_(l.NGAY_CHOT_DU_NO_DAU_KY),warnings:w,skip:skip};
 });
}
/** Xem trước đồng bộ (không ghi). period rỗng = tháng mới nhất có dữ liệu, không vượt quá tháng hiện tại. */
function getDebtSyncPreview(period){const ss=openFinanceSpreadsheet_();getCurrentUser_(ss);const m=debtSyncMonths_(readSheet_(ss,'LICH_TRA_NO',APP_MODULES.LICH_TRA_NO).rows),p=period?parsePeriod_(period).key:m.latest;if(!p)return{period:'',months:[],latest:'',cutoff:'',rows:[]};return{period:p,months:m.months,latest:m.latest,cutoff:periodLastDay_(p),rows:debtSyncCompute_(ss,p)};}
/** Đồng bộ: ghi Dư nợ sau khi trả (kỳ cuối tháng chốt) vào DU_NO_GOC_DAU_KY + NGAY_CHOT_DU_NO_DAU_KY = ngày cuối tháng. Server tự tính lại. */
function syncLoanBalances(period,loanIds){const p=parsePeriod_(period).key,c=periodLastDay_(p),ids=(loanIds||[]).map(String),lock=LockService.getScriptLock();if(!ids.length)throw new Error('Vui lòng chọn ít nhất một khoản vay.');lock.waitLock(30000);try{
 const ss=openFinanceSpreadsheet_(),kc=APP_MODULES.KHOAN_VAY,u=requirePermission_(ss,'write',kc);migrateLoanBase_(ss);
 const calc={};debtSyncCompute_(ss,p).forEach(function(r){calc[r.id]=r;});
 const sh=requireSheet_(ss,'KHOAN_VAY'),v=sh.getDataRange().getValues(),h=v[0].map(function(x){return String(x).trim();}),ii=h.indexOf(kc.idField),di=h.indexOf('DU_NO_GOC_DAU_KY'),ci=h.indexOf('NGAY_CHOT_DU_NO_DAU_KY');if(di<0||ci<0)throw new Error('Sheet KHOAN_VAY thiếu cột DU_NO_GOC_DAU_KY hoặc NGAY_CHOT_DU_NO_DAU_KY.');
 const now=new Date(),done=[];
 for(let r=1;r<v.length;r++){const id=String(v[r][ii]||'').trim(),x=calc[id];if(ids.indexOf(id)<0||!x||x.skip)continue;const row=v[r].slice();row[di]=x.newBalance;row[ci]=normalizeInput_(c,'NGAY_CHOT_DU_NO_DAU_KY',kc);setIfHeader_(row,h,'CAP_NHAT_LUC',now);sh.getRange(r+1,1,1,h.length).setValues([row]);done.push({id:id,name:x.name,bank:x.bank,contract:x.contract,old:x.current,nw:x.newBalance,lastId:x.lastId});writeAudit_(ss,'KHOAN_VAY',id,'DONG_BO_DU_NO','DU_NO_GOC_DAU_KY: '+x.current+' → '+x.newBalance+' | tháng '+p+' | kỳ cuối '+x.lastId+' | gốc ban đầu '+x.base+' − gốc phải trả lũy kế '+x.plan);}
 SpreadsheetApp.flush();invalidateModuleCache_('KHOAN_VAY');invalidateModuleCache_('LICH_TRA_NO');
 return{ok:true,period:p,cutoff:c,count:done.length,rows:done,before:done.reduce(function(n,x){return n+x.old;},0),after:done.reduce(function(n,x){return n+x.nw;},0),user:u.email};
}finally{lock.releaseLock();}}

/* ======================= V5.7 · NHẬP LỊCH TRẢ NỢ TỪ FILE ======================= */
const IMPORT_LABELS_={GOC_PHAI_TRA:'Gốc phải trả',LAI_PHAI_TRA:'Lãi phải trả',PHI_PHAI_TRA:'Phí phải trả',DIEU_CHINH_TANG_GIAM:'Điều chỉnh tăng/giảm'};
const IMPORT_FIELDS_=['MA_LICH_TRA','MA_KHOAN_VAY','KY_TRA_NO','NGAY_DEN_HAN','GOC_PHAI_TRA','LAI_PHAI_TRA','PHI_PHAI_TRA','DIEU_CHINH_TANG_GIAM','TRANG_THAI','GHI_CHU'],IMPORT_MONEY_=['GOC_PHAI_TRA','LAI_PHAI_TRA','PHI_PHAI_TRA','DIEU_CHINH_TANG_GIAM'];
function parseImportDate_(v){let s=String(v==null?'':v).trim(),m;if(!s)return'';if(/^\d{5}(\.\d+)?$/.test(s)){const d=new Date(Math.round((Number(s)-25569)*864e5));s=d.getUTCFullYear()+'-'+String(d.getUTCMonth()+1).padStart(2,'0')+'-'+String(d.getUTCDate()).padStart(2,'0');}let y,mo,da;if((m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/))){y=+m[1];mo=+m[2];da=+m[3];}else if((m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/))){y=+m[3];mo=+m[2];da=+m[1];}else return null;const d=new Date(y,mo-1,da);if(d.getFullYear()!==y||d.getMonth()!==mo-1||d.getDate()!==da)return null;return y+'-'+String(mo).padStart(2,'0')+'-'+String(da).padStart(2,'0');}
function parseImportNumber_(v){if(typeof v==='number')return v;let s=String(v==null?'':v).replace(/[\s₫đ]/gi,'');if(/^-?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else if(/^-?\d{1,3}(,\d{3})+(\.\d+)?$/.test(s))s=s.replace(/,/g,'');else s=s.replace(',','.');return s===''?NaN:Number(s);}
/** Kiểm tra từng dòng file nhập. Khóa trùng: Mã khoản vay + Kỳ tháng (mỗi khoản vay 1 kỳ / tháng, giống "Tạo tháng mới"). */
function scheduleImportCheck_(ss,rows){
 const c=APP_MODULES.LICH_TRA_NO,list=Array.isArray(rows)?rows:[];if(list.length>1000)throw new Error('Mỗi lần nhập tối đa 1.000 dòng.');
 const loans={},ids={},keys={},seen={},statuses=c.enums.TRANG_THAI;
 readSheet_(ss,'KHOAN_VAY',APP_MODULES.KHOAN_VAY).rows.forEach(function(l){loans[String(l.MA_KHOAN_VAY)]=l;});
 readSheet_(ss,'LICH_TRA_NO',c).rows.forEach(function(r){ids[String(r.MA_LICH_TRA)]=r;const p=periodKey_(r.NGAY_DEN_HAN);if(p&&String(r.TRANG_THAI)!=='HUY')keys[String(r.MA_KHOAN_VAY)+'|'+p]=String(r.MA_LICH_TRA);});
 return list.map(function(src,i){
  const d={},e=[],w=[];IMPORT_FIELDS_.forEach(function(f){d[f]=src&&src[f]!=null?String(src[f]).trim():'';});const line=Number(src&&src._line)||i+1;
  const loan=loans[d.MA_KHOAN_VAY];if(!d.MA_KHOAN_VAY)e.push('Thiếu mã khoản vay');else if(!loan)e.push('Mã khoản vay không tồn tại');else if(loan.TRANG_THAI==='DA_TAT_TOAN')e.push('Khoản vay đã tất toán');
  const date=parseImportDate_(src&&src.NGAY_DEN_HAN);if(!date)e.push(date===''?'Thiếu ngày đến hạn':'Ngày đến hạn không hợp lệ');else d.NGAY_DEN_HAN=date;
  if(!d.KY_TRA_NO&&date)d.KY_TRA_NO=date.slice(0,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(d.KY_TRA_NO))e.push('Kỳ trả nợ phải dạng YYYY-MM');else if(date&&date.slice(0,7)!==d.KY_TRA_NO)w.push('Ngày đến hạn không thuộc kỳ '+d.KY_TRA_NO);
  IMPORT_MONEY_.forEach(function(f){if(d[f]===''){d[f]=null;return;}const n=parseImportNumber_(src[f]);if(!isFinite(n))e.push(IMPORT_LABELS_[f]+' không phải số');else if(n<0&&f!=='DIEU_CHINH_TANG_GIAM')e.push(IMPORT_LABELS_[f]+' không được âm');d[f]=n;});
  if(d.TRANG_THAI&&statuses.indexOf(d.TRANG_THAI)<0)e.push('Trạng thái không hợp lệ');
  let action='add';const key=d.MA_KHOAN_VAY+'|'+(date?periodKey_(date):d.KY_TRA_NO);
  if(d.MA_LICH_TRA){const ex=ids[d.MA_LICH_TRA];if(!ex)e.push('Mã kỳ trả không tồn tại');else if(String(ex.MA_KHOAN_VAY)!==d.MA_KHOAN_VAY)e.push('Mã kỳ trả thuộc khoản vay khác');else action='update';}
  else if(seen[key])action='dupfile';else if(keys[key])action='dup';
  const dupWith=e.length?'':action==='dup'?keys[key]:action==='dupfile'?'dòng '+seen[key]:'';
  if(!d.MA_LICH_TRA&&!e.length&&!seen[key])seen[key]=line;
  return{line:line,action:e.length?'error':action,errors:e,warnings:w,data:d,bank:loan?loan.MA_NGAN_HANG||'':'',loanName:loan?loan.TEN_KHOAN_VAY||'':'',dupWith:dupWith};
 });
}
/** Dữ liệu để tạo file mẫu / file điền sẵn (trình duyệt dựng file .xlsx). sourcePeriod rỗng = file mẫu trống. */
function getScheduleImportContext(sourcePeriod){const ss=openFinanceSpreadsheet_();getCurrentUser_(ss);const loans=readSheetCached_(ss,'KHOAN_VAY',APP_MODULES.KHOAN_VAY).rows.filter(function(l){return l.TRANG_THAI!=='DA_TAT_TOAN';}).map(function(l){return{id:l.MA_KHOAN_VAY,name:l.TEN_KHOAN_VAY||'',bank:l.MA_NGAN_HANG||'',contract:l.SO_HOP_DONG||'',status:l.TRANG_THAI||''};});let rows=[],target='';if(sourcePeriod){const src=parsePeriod_(sourcePeriod),t=parsePeriod_(Utilities.formatDate(new Date(src.year,src.month,1),APP_CONFIG.timeZone,'yyyy-MM'));target=t.key;rows=readSheet_(ss,'LICH_TRA_NO',APP_MODULES.LICH_TRA_NO).rows.filter(function(r){return periodKey_(r.NGAY_DEN_HAN)===src.key&&String(r.TRANG_THAI)!=='HUY';}).sort(function(a,b){return String(a.MA_KHOAN_VAY).localeCompare(String(b.MA_KHOAN_VAY))||String(a.NGAY_DEN_HAN).localeCompare(String(b.NGAY_DEN_HAN));}).map(function(r){return{MA_LICH_TRA:'',MA_KHOAN_VAY:r.MA_KHOAN_VAY,KY_TRA_NO:t.key,NGAY_DEN_HAN:Utilities.formatDate(moveDateToPeriod_(r.NGAY_DEN_HAN,t),APP_CONFIG.timeZone,'yyyy-MM-dd'),GOC_PHAI_TRA:Number(r.GOC_PHAI_TRA)||0,LAI_PHAI_TRA:Number(r.LAI_PHAI_TRA)||0,PHI_PHAI_TRA:Number(r.PHI_PHAI_TRA)||0,DIEU_CHINH_TANG_GIAM:0,TRANG_THAI:'DU_KIEN',GHI_CHU:r.GHI_CHU||''};});}return{loans:loans,statuses:APP_MODULES.LICH_TRA_NO.enums.TRANG_THAI,source:sourcePeriod||'',target:target,rows:rows};}
/** Xem trước file nhập: không ghi gì. */
function previewScheduleImport(rows){const ss=openFinanceSpreadsheet_();getCurrentUser_(ss);return{rows:scheduleImportCheck_(ss,rows)};}
/** Nhập file: server kiểm tra lại toàn bộ rồi mới ghi. options.dup = 'skip' (mặc định) | 'add'. */
function importSchedules(rows,options){const opts=options||{},lock=LockService.getScriptLock();lock.waitLock(30000);try{
 const ss=openFinanceSpreadsheet_(),c=APP_MODULES.LICH_TRA_NO,u=requirePermission_(ss,'write',c),checked=scheduleImportCheck_(ss,rows),sh=requireSheet_(ss,'LICH_TRA_NO'),h=getHeaders_(sh);ensureRequiredHeaders_('LICH_TRA_NO',h);
 const v=sh.getDataRange().getValues(),ii=h.indexOf(c.idField),rowOf={};for(let r=1;r<v.length;r++)rowOf[String(v[r][ii]||'').trim()]=r;
 const now=new Date(),out=[],res={add:0,update:0,skip:0,error:0,errors:[],periods:{}};
 checked.forEach(function(x){
  if(x.action==='error'){res.error++;res.errors.push({line:x.line,data:x.data,msg:x.errors.join('; ')});return;}
  if(x.action==='dupfile'||(x.action==='dup'&&opts.dup!=='add')){res.skip++;return;}
  const d=x.data,put=function(row){IMPORT_FIELDS_.forEach(function(f){if(f===c.idField||d[f]===null||d[f]==='')return;setIfHeader_(row,h,f,f==='NGAY_DEN_HAN'?normalizeInput_(d[f],f,c):d[f]);});setIfHeader_(row,h,'CAP_NHAT_LUC',now);protectFormulaText_(row,h,c);return row;};
  if(x.action==='update'){const r=rowOf[d.MA_LICH_TRA];sh.getRange(r+1,1,1,h.length).setValues([put(v[r].slice())]);res.update++;}
  else{const row=put(new Array(h.length).fill(''));row[ii]=makeId_('LICH_TRA_NO');IMPORT_MONEY_.forEach(function(f){if(d[f]===null)setIfHeader_(row,h,f,0);});if(!d.TRANG_THAI)setIfHeader_(row,h,'TRANG_THAI','DU_KIEN');setIfHeader_(row,h,'NGUOI_TAO',u.email);setIfHeader_(row,h,'TAO_LUC',now);out.push(row);res.add++;}
  res.periods[d.KY_TRA_NO]=(res.periods[d.KY_TRA_NO]||0)+1;
 });
 if(out.length)sh.getRange(sh.getLastRow()+1,1,out.length,h.length).setValues(out);
 SpreadsheetApp.flush();writeAudit_(ss,'LICH_TRA_NO','NHAP_FILE','NHAP_FILE','Thêm '+res.add+'; cập nhật '+res.update+'; bỏ qua trùng '+res.skip+'; lỗi '+res.error);invalidateModuleCache_('LICH_TRA_NO');
 res.period=Object.keys(res.periods).sort(function(a,b){return res.periods[b]-res.periods[a];})[0]||'';return res;
}finally{lock.releaseLock();}}

function doGet(){return HtmlService.createHtmlOutputFromFile('index').setTitle(APP_CONFIG.title).addMetaTag('viewport','width=device-width, initial-scale=1, viewport-fit=cover').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);}// V5.8: Apps Script bỏ qua thẻ <meta viewport> trong file HTML, phải khai báo ở đây thì điện thoại mới nhận giao diện mobile
function getAppData(){const ss=openFinanceSpreadsheet_(),user=getCurrentUser_(ss),modules={},rows={};Object.keys(APP_MODULES).forEach(function(k){const c=APP_MODULES[k];if(c.adminOnly&&user.role!=='ADMIN')return;const d=readSheet_(ss,k,c);rows[k]=d.rows;modules[k]=Object.assign({},d.meta,{rows:d.rows});});return{title:APP_CONFIG.title,user:user,permissions:ROLE_RULES[user.role]||ROLE_RULES.VIEWER,modules:modules,summary:buildSummary_(rows),lookups:buildLookups_(rows)};}

function saveRecord(moduleKey,payload){const c=getModule_(moduleKey);if(c.readOnly)throw new Error('Phân hệ này chỉ cho phép xem.');if(!payload||typeof payload!=='object')throw new Error('Dữ liệu gửi lên không hợp lệ.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=openFinanceSpreadsheet_(),u=requirePermission_(ss,'write',c),sh=requireSheet_(ss,moduleKey);ensureAutoColumns_(sh,c);const h=getHeaders_(sh);ensureRequiredHeaders_(moduleKey,h);validatePayload_(c,payload);const idCol=h.indexOf(c.idField)+1,last=sh.getLastRow(),ids=last>=2?sh.getRange(2,idCol,last-1,1).getDisplayValues().map(function(r){return String(r[0]).trim();}):[];let id=String(payload[c.idField]||'').trim(),ix=id?ids.indexOf(id):-1,isNew=!id||(c.manualId&&ix<0);if(!isNew&&ix<0)throw new Error('Không tìm thấy bản ghi cần sửa.');if(isNew){id=c.manualId?id:makeId_(moduleKey);if(!id)throw new Error('Vui lòng nhập '+label_(c.idField)+'.');if(ids.indexOf(id)>=0)throw new Error('Mã đã tồn tại.');}const target=isNew?Math.max(2,last+1):ix+2,before=isNew?new Array(h.length).fill(''):sh.getRange(target,1,1,h.length).getValues()[0],row=before.slice(),protectedFields=['NGUOI_TAO','TAO_LUC','CAP_NHAT_LUC'];h.forEach(function(f,i){if(f===c.idField||protectedFields.indexOf(f)>=0||(c.calculated||[]).indexOf(f)>=0)return;if(Object.prototype.hasOwnProperty.call(payload,f))row[i]=normalizeInput_(payload[f],f,c);});row[h.indexOf(c.idField)]=id;const now=new Date();if(isNew){setIfHeader_(row,h,'NGUOI_TAO',u.email);setIfHeader_(row,h,'TAO_LUC',now);}setIfHeader_(row,h,'CAP_NHAT_LUC',now);applyCalculations_(moduleKey,row,h);protectFormulaText_(row,h,c);sh.getRange(target,1,1,h.length).setValues([row]);SpreadsheetApp.flush();writeAudit_(ss,moduleKey,id,isNew?'TAO_MOI':'CAP_NHAT',diffRows_(h,before,row));invalidateModuleCache_(moduleKey);if(moduleKey==='NGUOI_DUNG')invalidateUserCache_(id);return{ok:true,id:id,action:isNew?'created':'updated'};}finally{lock.releaseLock();}}
function deleteRecord(moduleKey,recordId){const c=getModule_(moduleKey),id=String(recordId||'').trim();if(!id)throw new Error('Thiếu mã bản ghi.');const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=openFinanceSpreadsheet_();requirePermission_(ss,'remove',c);if(c.readOnly)throw new Error('Không thể xóa dữ liệu hệ thống.');const sh=requireSheet_(ss,moduleKey),h=getHeaders_(sh),found=findRowById_(sh,h,c.idField,id);if(!found)throw new Error('Không tìm thấy bản ghi.');const si=h.indexOf('TRANG_THAI'),before=found.values.slice(),cancel=cancellationStatus_(c);if(si>=0&&cancel){found.values[si]=cancel;setIfHeader_(found.values,h,'CAP_NHAT_LUC',new Date());sh.getRange(found.row,1,1,h.length).setValues([found.values]);}else sh.deleteRow(found.row);writeAudit_(ss,moduleKey,id,si>=0&&cancel?'HUY_BAN_GHI':'XOA',diffRows_(h,before,si>=0&&cancel?found.values:[]));invalidateModuleCache_(moduleKey);if(moduleKey==='NGUOI_DUNG')invalidateUserCache_(id);return{ok:true};}finally{lock.releaseLock();}}
function approveRecord(moduleKey,recordId,decision,reason){const c=getModule_(moduleKey),id=String(recordId||'').trim(),action=String(decision||'').toUpperCase(),lock=LockService.getScriptLock();lock.waitLock(30000);try{const allowed=(c.enums||{}).TRANG_THAI||[];if(allowed.indexOf('DA_DUYET')<0)throw new Error('Phân hệ này không áp dụng quy trình phê duyệt.');const ss=openFinanceSpreadsheet_(),u=requirePermission_(ss,'approve',c),sh=requireSheet_(ss,moduleKey),h=getHeaders_(sh),si=h.indexOf('TRANG_THAI');if(si<0)throw new Error('Phân hệ không có trạng thái phê duyệt.');const found=findRowById_(sh,h,c.idField,id);if(!found)throw new Error('Không tìm thấy bản ghi.');const before=String(found.values[si]||''),after=action==='DUYET'?'DA_DUYET':action==='TU_CHOI'?'HUY':action==='TRINH_DUYET'?'CHO_DUYET':'';if(!after||allowed.indexOf(after)<0)throw new Error('Quyết định không hợp lệ.');found.values[si]=after;setIfHeader_(found.values,h,'CAP_NHAT_LUC',new Date());sh.getRange(found.row,1,1,h.length).setValues([found.values]);appendApproval_(ss,moduleKey,id,before,after,action,reason,u.email);writeAudit_(ss,moduleKey,id,'PHE_DUYET',before+' → '+after);invalidateModuleCache_(moduleKey);return{ok:true,status:after};}finally{lock.releaseLock();}}

/** V5.6.2: tự thêm cột mới (autoColumns) vào cuối hàng tiêu đề nếu sheet chưa có — không cần sửa sheet thủ công. */
function ensureAutoColumns_(sh,c){const add=(c&&c.autoColumns)||[];if(!add.length)return [];const h=getHeaders_(sh),miss=add.filter(function(f){return h.indexOf(f)<0;});if(!miss.length)return [];const need=h.length+miss.length;if(sh.getMaxColumns()<need)sh.insertColumnsAfter(sh.getMaxColumns(),need-sh.getMaxColumns());if(h.length)sh.getRange(1,h.length).copyFormatToRange(sh,h.length+1,need,1,1);sh.getRange(1,h.length+1,1,miss.length).setValues([miss]);return miss;}
/** CHẠY 1 LẦN trong trình soạn Apps Script: thêm các cột mới của Nguồn vốn vào dữ liệu gốc (sheet NGUON_VON):
 *  CO_THE_GIAI_NGAN, KHONG_THE_GIAI_NGAN, DU_NO_PHAI_TRA, GHI_CHU. Chọn hàm capNhatDataGoc_NguonVon → Chạy.
 *  An toàn khi chạy lại: cột đã có thì bỏ qua, không ghi đè dữ liệu. */
function capNhatDataGoc_NguonVon(){
 const ss=openFinanceSpreadsheet_(),c=APP_MODULES.NGUON_VON,sh=requireSheet_(ss,'NGUON_VON'),lock=LockService.getScriptLock();lock.waitLock(30000);
 try{
  const added=ensureAutoColumns_(sh,c),h=getHeaders_(sh),rows=Math.max(1,sh.getMaxRows()-1),info=[];
  c.autoColumns.forEach(function(f){const col=h.indexOf(f)+1;if(!col)throw new Error('Không tạo được cột '+f+'.');if((c.amounts||[]).indexOf(f)>=0)sh.getRange(2,col,rows,1).setNumberFormat('#,##0');info.push(f+'@'+col);});
  invalidateModuleCache_('NGUON_VON');
  const msg='Sheet NGUON_VON: '+(added.length?'đã thêm '+added.join(', '):'không cần thêm cột')+' · vị trí '+info.join(', ')+' · '+Math.max(0,sh.getLastRow()-1)+' dòng dữ liệu, giá trị cột mới để trống chờ nhập.';
  writeAudit_(ss,'NGUON_VON','CAU_TRUC','CAP_NHAT_CAU_TRUC',msg);console.log(msg);return msg;
 }finally{lock.releaseLock();}
}
function readSheet_(ss,key,c){ensureAutoColumns_(requireSheet_(ss,key),c);const sh=requireSheet_(ss,key),v=sh.getDataRange().getValues(),physical=(v[0]||[]).map(function(x){return String(x).trim();}),h=physical.concat((c.virtual||[]).filter(function(f){return physical.indexOf(f)<0;}));ensureRequiredHeaders_(key,physical);const clip=key==='NHAT_KY'?physical.indexOf('NOI_DUNG_THAY_DOI'):-1;if(clip>=0)v.forEach(function(r,i){if(i&&String(r[clip]).length>2000)r[clip]=String(r[clip]).slice(0,2000)+' …(xem đầy đủ trong sheet NHAT_KY)';});const body=v.slice(1),rows=(key==='NHAT_KY'?body.slice(-APP_CONFIG.maxLogRows):body.slice(0,APP_CONFIG.maxRowsPerModule)).filter(function(r){return String(r[physical.indexOf(c.idField)]||'').trim()!=='';}).map(function(r){const o={};physical.forEach(function(f,i){o[f]=serializeCell_(r[i],f);});(c.virtual||[]).forEach(function(f){if(!Object.prototype.hasOwnProperty.call(o,f))o[f]='';});return o;}),hidden=['NGUOI_TAO','TAO_LUC','CAP_NHAT_LUC'].concat(c.calculated||[]);return{rows:rows,meta:{title:c.title,group:c.group,idField:c.idField,headers:h,fields:h.filter(function(f){return f!==c.idField&&hidden.indexOf(f)<0;}),required:c.required||[],hidden:hidden,enums:c.enums||{},dates:c.dates||[],amounts:c.amounts||[],percents:c.percents||[],columns:(c.columns||h.slice(0,8)).filter(function(f){return h.indexOf(f)>=0;}),readOnly:!!c.readOnly,manualId:!!c.manualId}};}
function buildSummary_(r){const tx=r.GIAO_DICH_TIEN&&r.GIAO_DICH_TIEN.length?r.GIAO_DICH_TIEN:(r.THU_CHI||[]),done=tx.filter(function(x){return['DA_THUC_HIEN','HOAN_THANH','DA_DUYET'].indexOf(x.TRANG_THAI)>=0;}),inc=done.filter(function(x){return x.LOAI_GIAO_DICH==='THU';}).reduce(sum_('SO_TIEN'),0),exp=done.filter(function(x){return x.LOAI_GIAO_DICH==='CHI';}).reduce(sum_('SO_TIEN'),0),opening=(r.SO_DU_DAU_KY||[]).reduce(sum_('SO_DU'),0),plans=r.KE_HOACH_THU_CHI||[],pin=plans.filter(function(x){return x.LOAI_THU_CHI==='THU'&&x.TRANG_THAI!=='HUY';}).reduce(sum_('SO_TIEN_DU_KIEN'),0),pout=plans.filter(function(x){return x.LOAI_THU_CHI==='CHI'&&x.TRANG_THAI!=='HUY';}).reduce(sum_('SO_TIEN_DU_KIEN'),0),paid=indexSum_(r.PHAN_BO_CONG_NO||[],'MA_CONG_NO','SO_TIEN_PHAN_BO'),debts=r.CONG_NO||[],recv=debts.filter(function(x){return x.LOAI_CONG_NO==='PHAI_THU'&&x.TRANG_THAI!=='HUY';}).reduce(function(s,x){return s+Math.max(0,(Number(x.SO_TIEN_GOC)||0)-(paid[x.MA_CONG_NO]||0));},0),pay=debts.filter(function(x){return x.LOAI_CONG_NO==='PHAI_TRA'&&x.TRANG_THAI!=='HUY';}).reduce(function(s,x){return s+Math.max(0,(Number(x.SO_TIEN_GOC)||0)-(paid[x.MA_CONG_NO]||0));},0),lp=indexSum_(r.PHAN_BO_TRA_NO||[],'MA_LICH_TRA','GOC_DA_TRA'),due=(r.LICH_TRA_NO||[]).reduce(function(s,x){return s+Math.max(0,(Number(x.GOC_PHAI_TRA)||0)-(lp[x.MA_LICH_TRA]||0));},0);return{openingBalance:opening,actualIncome:inc,actualExpense:exp,currentBalance:opening+inc-exp,netCashFlow:inc-exp,plannedIncome:pin,plannedExpense:pout,forecastBalance:opening+inc-exp+pin-pout,receivable:recv,payable:pay,loanPrincipalDue:due,accountCount:(r.TAI_KHOAN||[]).filter(function(x){return x.TRANG_THAI!=='NGUNG_HOAT_DONG';}).length};}
function buildLookups_(rows){const out={};Object.keys(rows).forEach(function(k){const c=APP_MODULES[k];out[k]=(rows[k]||[]).slice(0,500).map(function(r){return{value:r[c.idField],label:r.TEN||r.TEN_TAI_KHOAN||r.TEN_KHOAN_VAY||r.HO_TEN||r.NOI_DUNG||r[c.idField]};});});return out;}
function sum_(f){return function(s,r){return s+(Number(r[f])||0);};}function indexSum_(rows,k,f){const m={};rows.forEach(function(r){m[r[k]]=(m[r[k]]||0)+(Number(r[f])||0);});return m;}
function validatePayload_(c,p){(c.required||[]).forEach(function(f){if(String(p[f]==null?'':p[f]).trim()==='')throw new Error('Vui lòng nhập '+label_(f)+'.');});Object.keys(c.enums||{}).forEach(function(f){const v=String(p[f]==null?'':p[f]).trim();if(v&&c.enums[f].indexOf(v)<0)throw new Error(label_(f)+' không hợp lệ.');});}
function cancellationStatus_(c){const a=(c.enums||{}).TRANG_THAI||[];return['HUY','NGUNG_HOAT_DONG','TAM_DUNG','KHONG_THUC_HIEN'].find(function(x){return a.indexOf(x)>=0;})||'';}
function applyCalculations_(key,row,h){if(key==='KHOAN_VAY'){const bi=h.indexOf('DU_NO_GOC_BAN_DAU');if(bi>=0&&!hasNum_(row[bi])){const d=row[h.indexOf('DU_NO_GOC_DAU_KY')],g=row[h.indexOf('TONG_GOC_GIAI_NGAN')];row[bi]=hasNum_(d)?Number(d):hasNum_(g)?Number(g):'';const ni=h.indexOf('NGAY_GOC_BAN_DAU'),ci=h.indexOf('NGAY_CHOT_DU_NO_DAU_KY');if(ni>=0&&ci>=0&&row[ni]===''&&hasNum_(d))row[ni]=row[ci];}}if(key==='NGUON_VON')setIfHeader_(row,h,'TONG_DU_KIEN',['SO_TIEN_DAT_DU_KIEN','SO_TIEN_XD_DU_KIEN','SO_TIEN_KHAC_DU_KIEN'].reduce(function(s,f){return s+(Number(row[h.indexOf(f)])||0);},0));}
function normalizeInput_(v,f,c){if(v==null||v==='')return '';if((c.dates||[]).indexOf(f)>=0){const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})(?:T(\d{2}):(\d{2}))?/);if(!m)throw new Error('Ngày không hợp lệ tại '+label_(f)+'.');return new Date(+m[1],+m[2]-1,+m[3],+(m[4]||12),+(m[5]||0),0);}if((c.amounts||[]).indexOf(f)>=0||(c.percents||[]).indexOf(f)>=0){const n=Number(v);if(!isFinite(n))throw new Error('Số không hợp lệ tại '+label_(f)+'.');if(n<0&&(c.allowNegative||[]).indexOf(f)<0)throw new Error(label_(f)+' không được âm.');return n;}return String(v).trim();}
function parsePeriod_(value){const m=String(value||'').match(/^(\d{4})-(0[1-9]|1[0-2])$/);if(!m)throw new Error('Kỳ tháng không hợp lệ.');return{year:+m[1],month:+m[2],key:m[1]+'-'+m[2]};}
function dateParts_(value){if(value instanceof Date&&!isNaN(value.getTime()))return{year:value.getFullYear(),month:value.getMonth()+1,day:value.getDate()};const m=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?{year:+m[1],month:+m[2],day:+m[3]}:null;}
function periodKey_(value){const p=dateParts_(value);return p?String(p.year)+'-'+String(p.month).padStart(2,'0'):'';}
function moveDateToPeriod_(value,period){const p=dateParts_(value);if(!p)throw new Error('Ngày đến hạn nguồn không hợp lệ.');const last=new Date(period.year,period.month,0).getDate();return new Date(period.year,period.month-1,Math.min(p.day,last),12,0,0);}
function protectFormulaText_(row,h,c){row.forEach(function(v,i){if(typeof v==='string'&&/^\s*[=+@]/.test(v)&&(c.dates||[]).indexOf(h[i])<0)row[i]="'"+v;});}
function serializeCell_(v,h){if(v instanceof Date&&!isNaN(v.getTime()))return Utilities.formatDate(v,APP_CONFIG.timeZone,/^(TAO_LUC|CAP_NHAT_LUC|THOI_GIAN)$/.test(h)?"yyyy-MM-dd'T'HH:mm:ss":'yyyy-MM-dd');return v==null?'':v;}
function getModule_(k){const c=APP_MODULES[String(k||'')];if(!c)throw new Error('Phân hệ không hợp lệ.');return c;}function openFinanceSpreadsheet_(){let real=null;const get=function(){return real||(real=SpreadsheetApp.openById(APP_CONFIG.spreadsheetId));};return{getSheetByName:function(n){return get().getSheetByName(n);}};}/* V5.9: chỉ mở bảng tính khi thật sự đọc/ghi sheet (dữ liệu có trong cache thì không mở) */function requireSheet_(ss,n){const sh=ss.getSheetByName(n);if(!sh)throw new Error('Không tìm thấy sheet '+n+'.');return sh;}function getHeaders_(sh){return sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0].map(function(v){return String(v).trim();});}function ensureRequiredHeaders_(k,h){const c=getModule_(k);[c.idField].concat(c.required||[]).forEach(function(f){if(h.indexOf(f)<0)throw new Error('Sheet '+k+' thiếu cột '+f+'.');});}
function findRowById_(sh,h,idf,id){const col=h.indexOf(idf)+1,last=sh.getLastRow();if(col<1||last<2)return null;const ids=sh.getRange(2,col,last-1,1).getDisplayValues();for(let i=0;i<ids.length;i++)if(String(ids[i][0]).trim()===id)return{row:i+2,values:sh.getRange(i+2,1,1,h.length).getValues()[0]};return null;}function setIfHeader_(row,h,n,v){const i=h.indexOf(n);if(i>=0)row[i]=v;}
function makeId_(k){const p={THU_CHI:'TC',TAI_KHOAN:'TK',SO_DU_DAU_KY:'SD',KE_HOACH_THU_CHI:'KH',GIAO_DICH_TIEN:'GD',NGUON_VON:'NV',KHOAN_VAY:'KV',LICH_SU_LAI_SUAT:'LS',LICH_TRA_NO:'LT',PHAN_BO_TRA_NO:'PT',CONG_NO:'CN',PHAN_BO_CONG_NO:'PC',CHUNG_TU:'CT',PHE_DUYET:'PD',NHAT_KY:'NK'}[k]||'ID';return p+'-'+Utilities.formatDate(new Date(),APP_CONFIG.timeZone,'yyMMdd-HHmmss')+'-'+Utilities.getUuid().slice(0,5).toUpperCase();}
function getCurrentUser_(ss){let email='';try{email=Session.getActiveUser().getEmail()||Session.getEffectiveUser().getEmail()||'';}catch(e){}const cache=CacheService.getScriptCache(),ck='USER_V51_'+email,hit=cacheGetJson_(cache,ck);if(hit)return hit;ss=ss||openFinanceSpreadsheet_();const sh=ss.getSheetByName('NGUOI_DUNG');let role='VIEWER',name=email;if(sh&&sh.getLastRow()>=2){const h=getHeaders_(sh),d=sh.getRange(2,1,sh.getLastRow()-1,h.length).getDisplayValues();d.some(function(r){if(String(r[h.indexOf('EMAIL')]).toLowerCase()===email.toLowerCase()&&r[h.indexOf('TRANG_THAI')]!=='NGUNG_HOAT_DONG'){role=r[h.indexOf('VAI_TRO')]||'VIEWER';name=r[h.indexOf('HO_TEN')]||email;return true;}return false;});}const out={email:email,name:name,role:role};cachePutJson_(cache,ck,out,1800);return out;}
function requirePermission_(ss,a,c){const u=getCurrentUser_(ss),r=ROLE_RULES[u.role]||ROLE_RULES.VIEWER;if(c.adminOnly&&u.role!=='ADMIN')throw new Error('Chỉ quản trị viên được thao tác.');if(!r[a])throw new Error('Tài khoản không có quyền thực hiện thao tác này.');return u;}
function appendApproval_(ss,type,id,before,after,decision,reason,email){const sh=ss.getSheetByName('PHE_DUYET');if(!sh)return;const h=getHeaders_(sh),o={MA_PHE_DUYET:makeId_('PHE_DUYET'),LOAI_BAN_GHI:type,MA_BAN_GHI:id,TRANG_THAI_TRUOC:before,TRANG_THAI_SAU:after,QUYET_DINH:decision,LY_DO:String(reason||''),EMAIL_NGUOI_DUYET:email,THOI_GIAN:new Date()};sh.appendRow(h.map(function(k){return Object.prototype.hasOwnProperty.call(o,k)?o[k]:'';}));invalidateModuleCache_('PHE_DUYET');}
function writeAudit_(ss,k,id,a,detail){try{const sh=ss.getSheetByName('NHAT_KY');if(!sh)return;const h=getHeaders_(sh),o={MA_NHAT_KY:makeId_('NHAT_KY'),THOI_GIAN:new Date(),EMAIL_NGUOI_DUNG:getCurrentUser_(ss).email,CHUC_NANG:(APP_MODULES[k]||{}).title||k,MA_BAN_GHI:id,HANH_DONG:a,NOI_DUNG_THAY_DOI:String(detail||'').slice(0,45000)};sh.appendRow(h.map(function(x){return Object.prototype.hasOwnProperty.call(o,x)?o[x]:'';}));invalidateModuleCache_('NHAT_KY');}catch(e){console.error(e);}}
function diffRows_(h,a,b){const d=[];h.forEach(function(k,i){const x=serializeCell_(a[i],k),y=serializeCell_(b[i],k);if(String(x)!==String(y))d.push(k+': '+String(x).slice(0,60)+' → '+String(y).slice(0,60));});return d.join('; ');}function label_(k){return String(k||'').replace(/_/g,' ').toLowerCase().replace(/^./,function(c){return c.toUpperCase();});}
